export const monsterListQuater = ["Aarakocra", "Abyssal Wretch", "Acolyte", "Apprentice Wizard", "Axe Beak", "Blink Dog", "Boar", "Bullywug", "Constrictor Snake", "Cow", "Deep Rothé", "Derro", "Dimetrodon", "Draft Horse", "Dretch", "Drow", "Duodrone", "Elk", "Flying Sword", "Giant Badger", "Giant Bat", "Giant Centipede", "Giant Frog", "Giant Lizard", "Giant Owl", "Giant Poisonous Snake", "Giant Wolf Spider", "Gnoll Witherling", "Goblin", "Grimlock", "Grung", "Hadrosaurus", "Kenku", "Kobold Inventor", "Kuo-toa", "Male Steeder", "Mud Mephit", "Needle Blight", "Oblex Spawn", "Ox", "Panther", "Pixie", "Pseudodragon", "Pteranodon", "Riding Horse", "Rothé", "Skeleton", "Smoke Mephit", "Sprite", "Star Spawn Grue", "Steam Mephit", "Stench Kow", "Swarm of Bats", "Swarm of Rats", "Swarm of Ravens", "The Wretched", "Troglodyte", "Vegepygmy", "Velociraptor", "Violet Fungus", "Winged Kobold", "Wolf", "Zombie"];

export const monsterListHalf = ["Ape", "Black Bear", "Chitine", "Cockatrice", "Crocodile", "Darkling", "Darkmantle", "Deep Gnome", "Dust Mephit", "Firenewt Warrior", "Gas Spore", "Gazer", "Gazer Familiar", "Giant Goat", "Giant Sea Horse", "Giant Wasp", "Gnoll", "Gnoll Hunter", "Gray Ooze", "Hobgoblin", "Ice Mephit", "Jackalwere", "Lizardfolk", "Magma Mephit", "Magmin", "Myconid Adult", "Nupperibo", "Orc", "Orc Nurtured One of Yurtrus", "Piercer", "Psychic Gray Ooze", "Reef Shark", "Rust", "Scout", "Shadow", "Skulk", "Swarm of Insects", "Swarm of Insects - Beetles", "Swarm of Insects - Centipedes", "Swarm of Insects - Spiders", "Swarm of Insects - Wasps", "Swarm of Rot Grubs", "Thug", "Tridrone", "Vine Blight", "Warhorse", "Warhorse Skeleton", "Worg"];

export const monsterList1 = ["Animated Armor", "Brass Dragon Wyrmling", "Bronze Scout", "Brown Bear", "Bugbear", "Choker", "Copper Dragon Wyrmling", "Death Dog", "Deinonychus", "Dire Wolf", "Dryad", "Duergar", "Duergar Soulblade", "Faerie Dragon - Younger", "Female Steeder", "Fire Snake", "Firenewt Warlock of Imix", "Ghoul", "Giant Eagle", "Giant Hyena", "Giant Octopus", "Giant Spider", "Giant Strider", "Giant Toad", "Giant Vulture", "Gnoll Flesh Gnawer", "Goblin Boss", "Grung Wildling", "Half-Ogre", "Harpy", "Hippogriff", "Imp", "Kobold Dragonshield", "Kobold Scale Sorcerer", "Kuo-toa Whip", "Lion", "Maw Demon", "Meazel", "Nilbog", "Nyxborn lynx", "Quadrone", "Quaggoth Spore Servant", "Quasit", "Quickling", "Scarecrow", "Sea Spawn", "Specter", "Spy", "Stone Cursed", "Swarm of Quippers", "Thorny", "Thri-kreen", "Tiger", "Vargouille", "Xvart Warlock of Raxivort", "Yuan-ti Pureblood"];

export const monsterList2 = ["Adult Kruthik", "Allosaurus", "Ankheg", "Aurochs", "Awakened Tree", "Azer", "Bandit Captain", "Bard", "Berbalang", "Berserker", "Black Dragon Wyrmling", "Black Guard Drake", "Blue Guard Drake", "Bronze Dragon Wyrmling", "Carrion Crawler", "Cave Bear", "Centaur", "Cult Fanatic", "Darkling Elder", "Druid", "Duergar Hammerer", "Duergar Kavalrachni", "Duergar Mind Master", "Duergar Stone Guard", "Duergar Xarrorn", "Ettercap", "Faerie Dragon - Older", "Gargoyle", "Gelatinous Cube", "Ghast", "Giant Boar", "Giant Constrictor Snake", "Giant Elk", "Gibbering Mouther", "Githzerai Monk", "Gnoll Pack Lord", "Green Dragon Wyrmling", "Green Guard Drake", "Grick", "Griffon", "Grung Elite Warrior", "Guard Drake", "Hobgoblin Iron Shadow", "Hunter Shark", "Intellect Devourer", "Lizardfolk Shaman", "Meenlock", "Merrow", "Mimic", "Minotaur Skeleton", "Myconid Sovereign", "Nothic", "Ochre Jelly", "Ogre", "Ogre Bolt Launcher", "Ogre Howdah", "Ogre Zombie", "Orc Claw of Luthic", "Orc Eye of Gruumsh", "Orc Hand of Yurtrus", "Orog", "Pegasus", "Pentadrone", "Peryton", "Plesiosaurus", "Polar Bear", "Poltergeist", "Priest", "Quaggoth", "Quetzalcoatlus", "Red Guard Drake", "Rhinoceros", "Rug of Smothering", "Rutterkin", "Saber-Toothed Tiger", "Sahuagin Priestess", "Sea Hag", "Shadow Mastiff", "Shadow Mastiff Alpha", "Silver Dragon Wyrmling", "Spined Devil", "Swarm of Poisonous Snakes", "Vegepygmy Chief", "Wererat", "White Dragon Wyrmling", "White Guard Drake", "Will-o-Wisp", "Yuan-ti Broodguard"];

export const monsterList3 = ["Ankylosaurus", "Archer", "Basilisk", "Bearded Devil", "Blue Dragon Wyrmling", "Bugbear Chief", "Bulezau", "Cave Fisher", "Choldrith", "Deathlock Wight", "Deep Scion", "Derro Savant", "Displacer Beast", "Doppelganger", "Duergar Screamer", "Flail Snail", "Giant Scorpion", "Giff", "Githyanki Warrior", "Gold Dragon Wyrmling", "Green Hag", "Grell", "Hell Hound", "Hobgoblin Captain", "Hook Horror", "Illusionist", "Killer Whale", "Knight", "Kuo-toa Monitor", "Leucrotta", "Manticore", "Martial Arts Adept", "Merrenoloth", "Minotaur", "Mummy", "Neogi", "Nightmare", "Ogre Chain Brute", "Orc Red Fang of Shargaas", "Owlbear", "Phase Spider", "Quaggoth Thonot", "Redcap", "Slithering Tracker", "Spectator", "Swashbuckler", "Sword Wraith Warrior", "Trapper", "Vampiric Mist", "Veteran", "Water Weird", "Werewolf", "Wight", "Winter Wolf", "Yeti", "Yuan-ti Malison"];

export const monsterList4 = ["Babau", "Banshee", "Barghest", "Black Pudding", "Bone Naga", "Chuul", "Couatl", "Deathlock", "Dybbuk", "Elephant", "Ettin", "Flameskull", "Ghost", "Girallon", "Gnoll Fang of Yeenoghu", "Guardian Wolf", "Helmed Horror", "Hobgoblin Devastator", "Incubus", "Iron Cobra", "Lamia", "Lizard King/Queen", "Merregon", "Neogi Master", "Ogre Battering Ram", "Orc Blade of Ilneval", "Orc War Chief", "Red Dragon Wyrmling", "Shadow Demon", "Stegosaurus", "Stone Defender", "Succubus", "Warlock of the Archfey", "Wereboar", "Weretiger", "Yeth Hound", "Yuan-ti Mind Whisperer", "Yuan-ti Nightmare Speaker"];

export const monsterList5 = ["Adult Oblex", "Air Elemental", "Allip", "Banderhobb", "Barbed Devil", "Barlgura", "Beholder Zombie", "Brontosaurus", "Bulette", "Cambion", "Catoblepas", "Drow Elite Warrior", "Dust Devil", "Earth Elemental", "Enchanter", "Fire Elemental", "Flesh Golem", "Giant Crocodile", "Giant Shark", "Gladiator", "Gorgon", "Half-Red Dragon Veteran", "Hill Giant", "Kraken Priest", "Kruthik Hive Lord", "Master Thief", "Mezzoloth", "Mindwitness", "Night Hag", "Oaken Bolter", "Otyugh", "Red Slaad", "Revenant", "Roper", "Sahuagin Baron", "Salamander", "Shambling Mound", "Spawn of Kyuss", "Star Spawn Mangler", "Swarm of Cranium Rats", "Tanarukk", "Tlincalli", "Transmuter", "Triceratops", "Troll", "Umber Hulk", "Unicorn", "Vampire Spawn", "Water Elemental", "Werebear", "Wood Woad", "Wraith", "Xorn", "Young Remorhaz"];

export const monsterList6 = ["Annis Hag", "Bodak", "Chasme", "Chimera", "Conjurer Wizard", "Cyclops", "Drider", "Duergar Warlord", "Galeb Duhr", "Gauth", "Githzerai Zerth", "Hobgoblin Warlord", "Invisible Stalker", "Kuo-toa Archpriest", "Mage", "Mammoth", "Medusa", "Vrock", "White Abishai", "Wyvern", "Young Brass Dragon", "Young White Dragon,"];

export const monsterList7 = ["Air Elemental Myrmidon", "Armanite", "Bheur Hag", "Black Abishai", "Blue Slaad", "Blue Slaad (control gem variant)", "Dhergoloth", "Draegloth", "Drow Mage", "Earth Elemental Myrmidon", "Fire Elemental Myrmidon", "Giant Ape", "Grick Alpha", "Korred", "Lost Sorrowsworn", "Maurezhi", "Mind Flayer", "Night Hag (Coven Variant)", "Oni", "Shadar-kai Shadow Dancer", "Shield Guardian", "Stone Giant", "Venom Troll", "Warlock of the Fiend", "Water Elemental Myrmidon", "Young Black Dragon", "Young Copper Dragon", "Yuan-ti Abomination"];

export const monsterList8 = ["Assassin", "Blackguard", "Canoloth", "Chain Devil", "Cloaker", "Corpse Flower", "Deathlock Mastermind", "Diviner Wizard", "Drow Priestess of Lolth", "Fomorian", "Frost Giant", "Githyanki Knight", "Green Slaad", "Hezrou", "Howler", "Hydra", "Mind Flayer Arcanist", "Shoosuva", "Spirit Naga", "Sword Wraith Commander", "Tyrannosaurus Rex", "Young Bronze Dragon", "Young Green Dragon"];

export const monsterList9 = ["Abjurer Wizard", "Abominable Yeti", "Bone Devil", "Champion", "Clay Golem", "Cloud Giant", "Drow House Captain", "Evoker Wizard", "Fire Giant", "Flind", "Frost Salamander", "Glabrezu", "Gray Slaad", "Hydroloth", "Lonely Sorrowsworn", "Necromancer Wizard", "Nycaloth", "Rot Troll", "Shadar-kai Gloom Weaver", "Treant", "Ulitharid", "War Priest", "Young Blue Dragon", "Young Silver Dragon"];

export const monsterList10 = ["Aboleth", "Alhoon", "Autumn Eladrin", "Death Kiss", "Death Slaad", "Deva", "Elder Oblex", "Froghemoth", "Githyanki Gish", "Githzerai Enlightened", "Guardian Naga", "Orthon", "Spring Eladrin", "Star Spawn Hulk", "Stone Giant Dreamwalker", "Stone Golem", "Summer Eladrin", "Winter Eladrin", "Yochlol", "Young Gold Dragon", "Young Red Dragon"];

export const monsterList11 = ["Alkilith", "Balhannoth", "Behir", "Cloud Giant Smiling One", "Dao", "Djinni", "Drow Shadowblade", "Efreeti", "Gynosphinx", "Horned Devil", "Hungry Sorrowsworn", "Marid", "Morkoth", "Remorhaz", "Roc", "Shadar-kai Soul Monger", "Spirit Troll", "Yagnoloth"];

export const monsterList12 = ["Arcanaloth", "Archdruid", "Archmage", "Boneclaw", "Duergar Despot", "Eidolon", "Erinyes", "Frost Giant Everlasting One", "Githyanki Kith’rak", "Gray Render", "Ki-rin", "Oinoloth", "Sacred Statue", "Warlord", "Yuan-ti Anathema"];

export const monsterList13 = ["Adult Brass Dragon", "Adult White Dragon", "Angry Sorrowsworn", "Beholder", "Devourer", "Dire Troll", "Drow Arachnomancer", "Nalfeshnee", "Narzugon", "Neothelid", "Rakshasa", "Star Spawn Seer", "Ultroloth", "Vampire", "Wastrilith", "Young Red Shadow Dragon"];

export const monsterList14 = ["Adult Black Dragon", "Adult Copper Dragon", "Cadaver Collector", "Death Tyrant", "Drow Inquisitor", "Elder Brain", "Fire Giant Dreadnought", "Githyanki Supreme Commander", "Ice Devil", "Retriever"];

export const monsterList15 = ["Adult Bronze Dragon", "Adult Green Dragon", "Green Abishai", "Mummy Lord", "Nabassu", "Purple Worm", "Skull Lord", "Vampire Spellcaster", "Vampire Warrior"];

export const monsterList16 = ["Adult Blue Dragon", "Adult Silver Dragon", "Githzerai Anarch", "Hellfire Engine", "Iron Golem", "Marilith", "Phoenix", "Planetar", "Star Spawn Larva Mage", "Steel Predator", "Storm Giant Quintessent", "Titivilus"];

export const monsterList17 = ["Adult Blue Dracolich", "Adult Gold Dragon", "Adult Red Dracolich", "Adult Red Dragon", "Androsphinx", "Blue Abishai", "Death Knight", "Dragon Turtle", "Goristro", "Nagpa"];
