export const monsterListQuater = ["Aarakocra", "Abyssal Wretch", "Acolyte", "Apprentice Wizard", "Axe Beak", "Blink Dog", "Boar", "Bullywug", "Constrictor Snake", "Cow", "Deep Rothé", "Derro", "Dimetrodon", "Draft Horse", "Dretch", "Drow", "Duodrone", "Elk", "Flying Sword", "Giant Badger", "Giant Bat", "Giant Centipede", "Giant Frog", "Giant Lizard", "Giant Owl", "Giant Poisonous Snake", "Giant Wolf Spider", "Gnoll Witherling", "Goblin", "Grimlock", "Grung", "Hadrosaurus", "Kenku", "Kobold Inventor", "Kuo-toa", "Male Steeder", "Mud Mephit", "Needle Blight", "Oblex Spawn", "Ox", "Panther", "Pixie", "Pseudodragon", "Pteranodon", "Riding Horse", "Rothé", "Skeleton", "Smoke Mephit", "Sprite", "Star Spawn Grue", "Steam Mephit", "Stench Kow", "Swarm of Bats", "Swarm of Rats", "Swarm of Ravens", "The Wretched", "Troglodyte", "Vegepygmy", "Velociraptor", "Violet Fungus", "Winged Kobold", "Wolf", "Zombie"];

export const monsterListHalf = ["Ape", "Black Bear", "Chitine", "Cockatrice", "Crocodile", "Darkling", "Darkmantle", "Deep Gnome", "Dust Mephit", "Firenewt Warrior", "Gas Spore", "Gazer", "Gazer Familiar", "Giant Goat", "Giant Sea Horse", "Giant Wasp", "Gnoll", "Gnoll Hunter", "Gray Ooze", "Hobgoblin", "Ice Mephit", "Jackalwere", "Lizardfolk", "Magma Mephit", "Magmin", "Myconid Adult", "Nupperibo", "Orc", "Orc Nurtured One of Yurtrus", "Piercer", "Psychic Gray Ooze", "Reef Shark", "Rust", "Scout", "Shadow", "Skulk", "Swarm of Insects", "Swarm of Insects - Beetles", "Swarm of Insects - Centipedes", "Swarm of Insects - Spiders", "Swarm of Insects - Wasps", "Swarm of Rot Grubs", "Thug", "Tridrone", "Vine Blight", "Warhorse", "Warhorse Skeleton", "Worg"];

export const monsterList1 = ["Animated Armor", "Brass Dragon Wyrmling", "Bronze Scout", "Brown Bear", "Bugbear", "Choker", "Copper Dragon Wyrmling", "Death Dog", "Deinonychus", "Dire Wolf", "Dryad", "Duergar", "Duergar Soulblade", "Faerie Dragon - Younger", "Female Steeder", "Fire Snake", "Firenewt Warlock of Imix", "Ghoul", "Giant Eagle", "Giant Hyena", "Giant Octopus", "Giant Spider", "Giant Strider", "Giant Toad", "Giant Vulture", "Gnoll Flesh Gnawer", "Goblin Boss", "Grung Wildling", "Half-Ogre", "Harpy", "Hippogriff", "Imp", "Kobold Dragonshield", "Kobold Scale Sorcerer", "Kuo-toa Whip", "Lion", "Maw Demon", "Meazel", "Nilbog", "Nyxborn lynx", "Quadrone", "Quaggoth Spore Servant", "Quasit", "Quickling", "Scarecrow", "Sea Spawn", "Specter", "Spy", "Stone Cursed", "Swarm of Quippers", "Thorny", "Thri-kreen", "Tiger", "Vargouille", "Xvart Warlock of Raxivort", "Yuan-ti Pureblood"];

export const monsterList2 = ["Adult Kruthik", "Allosaurus", "Ankheg", "Aurochs", "Awakened Tree", "Azer", "Bandit Captain", "Bard", "Berbalang", "Berserker", "Black Dragon Wyrmling", "Black Guard Drake", "Blue Guard Drake", "Bronze Dragon Wyrmling", "Carrion Crawler", "Cave Bear", "Centaur", "Cult Fanatic", "Darkling Elder", "Druid", "Duergar Hammerer", "Duergar Kavalrachni", "Duergar Mind Master", "Duergar Stone Guard", "Duergar Xarrorn", "Ettercap", "Faerie Dragon - Older", "Gargoyle", "Gelatinous Cube", "Ghast", "Giant Boar", "Giant Constrictor Snake", "Giant Elk", "Gibbering Mouther", "Githzerai Monk", "Gnoll Pack Lord", "Green Dragon Wyrmling", "Green Guard Drake", "Grick", "Griffon", "Grung Elite Warrior", "Guard Drake", "Hobgoblin Iron Shadow", "Hunter Shark", "Intellect Devourer", "Lizardfolk Shaman", "Meenlock", "Merrow", "Mimic", "Minotaur Skeleton", "Myconid Sovereign", "Nothic", "Ochre Jelly", "Ogre", "Ogre Bolt Launcher", "Ogre Howdah", "Ogre Zombie", "Orc Claw of Luthic", "Orc Eye of Gruumsh", "Orc Hand of Yurtrus", "Orog", "Pegasus", "Pentadrone", "Peryton", "Plesiosaurus", "Polar Bear", "Poltergeist", "Priest", "Quaggoth", "Quetzalcoatlus", "Red Guard Drake", "Rhinoceros", "Rug of Smothering", "Rutterkin", "Saber-Toothed Tiger", "Sahuagin Priestess", "Sea Hag", "Shadow Mastiff", "Shadow Mastiff Alpha", "Silver Dragon Wyrmling", "Spined Devil", "Swarm of Poisonous Snakes", "Vegepygmy Chief", "Wererat", "White Dragon Wyrmling", "White Guard Drake", "Will-o-Wisp", "Yuan-ti Broodguard"];

export const monsterList3 = ["Ankylosaurus", "Archer", "Basilisk", "Bearded Devil", "Blue Dragon Wyrmling", "Bugbear Chief", "Bulezau", "Cave Fisher", "Choldrith", "Deathlock Wight", "Deep Scion", "Derro Savant", "Displacer Beast", "Doppelganger", "Duergar Screamer", "Flail Snail", "Giant Scorpion", "Giff", "Githyanki Warrior", "Gold Dragon Wyrmling", "Green Hag", "Grell", "Hell Hound", "Hobgoblin Captain", "Hook Horror", "Illusionist", "Killer Whale", "Knight", "Kuo-toa Monitor", "Leucrotta", "Manticore", "Martial Arts Adept", "Merrenoloth", "Minotaur", "Mummy", "Neogi", "Nightmare", "Ogre Chain Brute", "Orc Red Fang of Shargaas", "Owlbear", "Phase Spider", "Quaggoth Thonot", "Redcap", "Slithering Tracker", "Spectator", "Swashbuckler", "Sword Wraith Warrior", "Trapper", "Vampiric Mist", "Veteran", "Water Weird", "Werewolf", "Wight", "Winter Wolf", "Yeti", "Yuan-ti Malison"];

export const monsterList4 = ["Babau", "Banshee", "Barghest", "Black Pudding", "Bone Naga", "Chuul", "Couatl", "Deathlock", "Dybbuk", "Elephant", "Ettin", "Flameskull", "Ghost", "Girallon", "Gnoll Fang of Yeenoghu", "Guardian Wolf", "Helmed Horror", "Hobgoblin Devastator", "Incubus", "Iron Cobra", "Lamia", "Lizard King/Queen", "Merregon", "Neogi Master", "Ogre Battering Ram", "Orc Blade of Ilneval", "Orc War Chief", "Red Dragon Wyrmling", "Shadow Demon", "Stegosaurus", "Stone Defender", "Succubus", "Warlock of the Archfey", "Wereboar", "Weretiger", "Yeth Hound", "Yuan-ti Mind Whisperer", "Yuan-ti Nightmare Speaker"];

export const monsterList5 = ["Adult Oblex", "Air Elemental", "Allip", "Banderhobb", "Barbed Devil", "Barlgura", "Beholder Zombie", "Brontosaurus", "Bulette", "Cambion", "Catoblepas", "Drow Elite Warrior", "Dust Devil", "Earth Elemental", "Enchanter", "Fire Elemental", "Flesh Golem", "Giant Crocodile", "Giant Shark", "Gladiator", "Gorgon", "Half-Red Dragon Veteran", "Hill Giant", "Kraken Priest", "Kruthik Hive Lord", "Master Thief", "Mezzoloth", "Mindwitness", "Night Hag", "Oaken Bolter", "Otyugh", "Red Slaad", "Revenant", "Roper", "Sahuagin Baron", "Salamander", "Shambling Mound", "Spawn of Kyuss", "Star Spawn Mangler", "Swarm of Cranium Rats", "Tanarukk", "Tlincalli", "Transmuter", "Triceratops", "Troll", "Umber Hulk", "Unicorn", "Vampire Spawn", "Water Elemental", "Werebear", "Wood Woad", "Wraith", "Xorn", "Young Remorhaz"];