$(document).ready(function(){
    var tropes = [["/pmwiki/pmwiki.php/Main/OneDimensionalThinking", "1-Dimensional Thinking", "TV characters when being chased by anything that is limited to one direction (e.g. a boulder) never just step out of its path. They always run straight ahead and try to outrun it."],
["/pmwiki/pmwiki.php/Main/TenMinuteRetirement", "10-Minute Retirement", "The hero gives up on his mission only to come back when a situation arises that requires his help."],
["/pmwiki/pmwiki.php/Main/AbsurdlySharpBlade", "Absurdly Sharp Blade", "A blade that is somehow so sharp that it can cut through almost anything and never get dull."],
["/pmwiki/pmwiki.php/Main/AcousticLicense", "Acoustic License", "Cool dialogue will always be heard above the din of car chases and explosions."],
["/pmwiki/pmwiki.php/Main/AcquiredPoisonImmunity", "Acquired Poison Immunity", "The development of immunity to a particular drug or poison by taking small doses for a long time."],
["/pmwiki/pmwiki.php/Main/AcrophobicBird", "Acrophobic Bird", "When escaping danger a character who can fly will never think about flying up."],
["/pmwiki/pmwiki.php/Main/ActionDad", "Action Dad", "When someone's father gets in on the action."],
["/pmwiki/pmwiki.php/Main/ActionDressRip", "Action Dress Rip", "When an Action Girl finds herself in a dress she'll rip it before going into a situation that actually requires action."],
["/pmwiki/pmwiki.php/Main/ActionFilmQuietDramaScene", "Action Film Quiet Drama Scene", "That bit where you actually watch the actors instead of the special effects."],
["/pmwiki/pmwiki.php/Main/ActionGirl", "Action Girl", "A girl who is as much of a badass as any of the boys."],
["/pmwiki/pmwiki.php/Main/ActionHoggingOpening", "Action-Hogging Opening", "When an action adventure show has more action of a higher quality in the opening sequence than in an entire episode."],
["/pmwiki/pmwiki.php/Main/ActionInsuranceGag", "Action Insurance Gag", "Lampshading the explosive or destructive sequences in action-oriented works by way of reference to insurance or mortgage payments"],
["/pmwiki/pmwiki.php/Main/ActionMom", "Action Mom", "When someone's mother gets in on the action."],
["/pmwiki/pmwiki.php/Main/AdrenalineMakeover", "Adrenaline Makeover", "When a shy or frumpy girl is embroiled in an adventure by the end of it she has come out of her shell and often gotten sexier and/or more badass."],
["/pmwiki/pmwiki.php/Main/AfterActionHealingDrama", "After-Action Healing Drama", "When bad even possibly lethal injuries are treated in a dramatic scene after one of heavy action."],
["/pmwiki/pmwiki.php/Main/AfterActionPatchup", "After Action Patchup", "When the injured hero gets his injuries treated in a quiet scene after one of heavy action."],
["/pmwiki/pmwiki.php/Main/AirVentPassageway", "Air-Vent Passageway", "When heroes find themselves trapped in a room with all doors and windows locked the quickest exit is always through the ventilation duct."],
["/pmwiki/pmwiki.php/Main/AllYourBaseAreBelongToUs", "All Your Base Are Belong to Us", "Where the heroes", "home base is attacked."],
["/pmwiki/pmwiki.php/Main/AlmostOutOfOxygen", "Almost Out of Oxygen", "Imminent death by suffocation is always a good way to ratchet up the tension."],
["/pmwiki/pmwiki.php/Main/AloofAlly", "Aloof Ally", "An ally who is mistrustful or can't be bothered with your group preferring to do things on their own; he generally joins up at some point though."],
["/pmwiki/pmwiki.php/Main/AlwaysABiggerFish", "Always a Bigger Fish", "Where the heroes are saved from a scary monster by a scarier monster."],
["/pmwiki/pmwiki.php/Main/AlwaysOnDuty", "Always on Duty", "No matter what time of day or night the main cast are always the ones on duty ready to deal with problems."],
["/pmwiki/pmwiki.php/Main/AlwaysSaveTheGirl", "Always Save the Girl", "Where the hero values the life of their love interest over absolutely everything else often including the rest of the world."],
["/pmwiki/pmwiki.php/Main/AmericaSavesTheDay", "America Saves the Day", "Aliens (or other villains) are threatening the entire world - but it's up to the USA to beat them!"],
["/pmwiki/pmwiki.php/Main/AndMissionControlRejoiced", "And Mission Control Rejoiced", "When Mission Control is seriously impressed by the hero's actions."],
["/pmwiki/pmwiki.php/Main/TheAnticipator", "The Anticipator", "When a character dramatically expects or waits for another to sneak up on them."],
["/pmwiki/pmwiki.php/Main/AnAssKickingChristmas", "An Ass-Kicking Christmas", "The habit of some action works to take place around Christmas time."],
["/pmwiki/pmwiki.php/Main/BadGuyBar", "Bad-Guy Bar", "This is the place where bad guys hang out to plot their nefarious deeds."],
["/pmwiki/pmwiki.php/Main/BadHabits", "Bad Habits", "Where heroes or villains dress up as a religious figure as part of a disguise."],
["/pmwiki/pmwiki.php/Main/BadassDriver", "Badass Driver", "These guys can pull things behind the wheel that you'd love to be able to do (though not necessarily to be in the passenger's seat at the time)."],
["/pmwiki/pmwiki.php/Main/TheBait", "The Bait", "The character used to draw out the bad guys for a trap. Often the Butt-Monkey's job."],
["/pmwiki/pmwiki.php/Main/BandOfBrothers", "Band of Brothers", "The danger of the situation has forged a friendship between the Heroes and his companions that transcends the usual meaning of the word."],
["/pmwiki/pmwiki.php/Main/BangingForHelp", "Banging for Help", "A trapped character does this to attract attention from people outside."],
["/pmwiki/pmwiki.php/Main/BarSlide", "Bar Slide", "The bartender slides the cup mug or shot glass across the bar to a patron."],
["/pmwiki/pmwiki.php/Main/BarrierBustingBlow", "Barrier-Busting Blow", "A super-strong character or monster just punches through a door or wall to reach the victim on the other side."],
["/pmwiki/pmwiki.php/Main/BathroomBreakOut", "Bathroom Break-Out", "A character makes his escape by ducking into the John."],
["/pmwiki/pmwiki.php/Main/BeastInTheMaze", "Beast in the Maze", "A character must avoid a horrific monster within a complex labyrinth."],
["/pmwiki/pmwiki.php/Main/BigDamnHeroes", "Big Damn Heroes", "The heroic swoop to save the day just in the nick of time."],
["/pmwiki/pmwiki.php/Main/BigHeroicRun", "Big Heroic Run", "In which the hero runs at full tilt to save the day or fulfill his goals usually scored with a rousing fanfare."],
["/pmwiki/pmwiki.php/Main/Blaxploitation", "Blaxploitation", "A type of action movie made in the 1970s and '80s where the heroes are always black."],
["/pmwiki/pmwiki.php/Main/BlaxploitationParody", "Blaxploitation Parody", "Making fun of the Blaxploitation genre."],
["/pmwiki/pmwiki.php/Main/BloodlessCarnage", "Bloodless Carnage", "When someone is shot they show no wounds or blood they just crumple up and fall on the floor."],
["/pmwiki/pmwiki.php/Main/BluffTheImpostor", "Bluff the Impostor", "You think someone is acting like an impostor so you say something to them with an erroneous fact and see if they react to it."],
["/pmwiki/pmwiki.php/Main/BodybagTrick", "Bodybag Trick", "When a character hides in a bodybag and is wheeled into a hospital or other facility then gets out and does his/her mission."],
["/pmwiki/pmwiki.php/Main/BodyguardBabes", "Bodyguard Babes", "Where the most elite defenders of the Big Bad are exclusively female warriors."],
["/pmwiki/pmwiki.php/Main/BoldExplorer", "Bold Explorer", "A person whose actions usually lead to action and adventure."],
["/pmwiki/pmwiki.php/Main/BolivianArmyEnding", "Bolivian Army Ending", "The ending of an episode season character arc or especially entire series that ends in an open-ended tragedy."],
["/pmwiki/pmwiki.php/Main/BombDisposal", "Bomb Disposal", "Techniques are used to dispose of bombs regardless if it was disarmed or not."],
["/pmwiki/pmwiki.php/Main/BombersOnTheScreen", "Bombers on the Screen", "A real-time computer map is used showing the positions of military units (or possibly a physical map with model units)."],
["/pmwiki/pmwiki.php/Main/BombproofAppliance", "Bombproof Appliance", "When a bomb is going to go off indoors the hero hides in a bathtub or fridge."],
["/pmwiki/pmwiki.php/Main/BondOneLiner", "Bond One-Liner", "A pithy line said by the hero just after he's killed a bad guy."],
["/pmwiki/pmwiki.php/Main/BondVillainStupidity", "Bond Villain Stupidity", "When a villain fails to kill the hero when they have him cornered or captured."],
["/pmwiki/pmwiki.php/Main/BookcasePassage", "Bookcase Passage", "A secret passage is hidden behind a bookcase or triggered by the removal or manipulation of a book in a bookcase."],
["/pmwiki/pmwiki.php/Main/BoomerangComeback", "Boomerang Comeback", "The thrown weapon that you thought missed its target is coming back around for a second go."],
["/pmwiki/pmwiki.php/Main/BottledHeroicResolve", "Bottled Heroic Resolve", "A drug or potion to allow severely injured heroes to get back on their feet and finish off the bad guy."],
["/pmwiki/pmwiki.php/Main/BoundAndGagged", "Bound and Gagged", "don't you hate it when you get all tied up with things?"],
["/pmwiki/pmwiki.php/Main/BreakOutTheMuseumPiece", "Break Out the Museum Piece", "When the modern weaponry or equipment has been destroyed or taken away the heroes resort to outdated stuff to do the job."],
["/pmwiki/pmwiki.php/Main/BreakTheBadass", "Break the Badass", "When you want to show that the situation is horrible make sure your toughest character is scared!"],
["/pmwiki/pmwiki.php/Main/BreakingTheBonds", "Breaking the Bonds", "Heroes showing off their power by busting out of chains ropes or similar restraints."],
["/pmwiki/pmwiki.php/Main/BringNewsBack", "Bring News Back", "Where a character must go back in person (often through long dangerous roads) to deliver important news."],
["/pmwiki/pmwiki.php/Main/BulletCatch", "Bullet Catch", "Catching bullets translates into instant badass."],
["/pmwiki/pmwiki.php/Main/BulletproofHumanShield", "Bulletproof Human Shield", "Grab a nearby Mook and let him block bullets while you head for safety."],
["/pmwiki/pmwiki.php/Main/CableCarActionSequence", "Cable-Car Action Sequence", "A fight aboard or atop a moving gondola at great height."],
["/pmwiki/pmwiki.php/Main/CacophonyCoverUp", "Cacophony Cover Up", "Remain unheard thanks to a nearby louder noise."],
["/pmwiki/pmwiki.php/Main/CantBatheWithoutAWeapon", "Can't Bathe Without a Weapon", "The hero(ine) may need to undress to take a bath but won't ever get caught without a weapon."],
["/pmwiki/pmwiki.php/Main/CapturedByCannibals", "Captured by Cannibals", "Can the heroes escape in time to avoid becoming the main course?"],
["/pmwiki/pmwiki.php/Main/CarCushion", "Car Cushion", "The higher you are falling from the more likely it is that a car will be there when you land."],
["/pmwiki/pmwiki.php/Main/CarnivalOfKillers", "Carnival of Killers", "When a series of assassins goes after the hero either from a bounty offer or hired by the villain."],
["/pmwiki/pmwiki.php/Main/CasualDangerDialog", "Casual Danger Dialog", "Where heroes in danger will crack jokes or speak casually rather than gibbering in terror."],
["/pmwiki/pmwiki.php/Main/CatchAFallingStar", "Catch a Falling Star", "If the hero falls from too high a point he will inevitably be rescued."],
["/pmwiki/pmwiki.php/Main/CaughtInASnare", "Caught in a Snare", "Exactly what it looks like the hero or someone else gets caught in a tree snare or other boobytrap."],
["/pmwiki/pmwiki.php/Main/TheCavalry", "The Cavalry", "Where the heroes are saved in the last minute by other characters."],
["/pmwiki/pmwiki.php/Main/TheCavalryArrivesLate", "The Cavalry Arrives Late", "...and usually only after the hero has dealt with the threat that needed their attention."],
["/pmwiki/pmwiki.php/Main/CavalryBetrayal", "Cavalry Betrayal", "Where apparent rescuers turn out to be actually siding with the villain."],
["/pmwiki/pmwiki.php/Main/CavalryRefusal", "Cavalry Refusal", "Where potential rescuers refuse to help the heroes."],
["/pmwiki/pmwiki.php/Main/CaveMouth", "Cave Mouth", "When a cave's mouth looks like an actual mouth usually that of a monster."],
["/pmwiki/pmwiki.php/Main/CeilingCling", "Ceiling Cling", "A character avoids pursuit or detection by hanging from the ceiling of the room or hallway."],
["/pmwiki/pmwiki.php/Main/CeilingSmash", "Ceiling Smash", "A character is smashed into a ceiling."],
["/pmwiki/pmwiki.php/Main/TheCenterpieceSpectacular", "The Centerpiece Spectacular", "An exciting set piece staged in Act 2 of a work to keep the audience excited enough to pay attention through the entire work."],
["/pmwiki/pmwiki.php/Main/TheChainOfHarm", "The Chain of Harm", "Any time a hero stops a villain's plans and he takes it out not on the hero or his friends but on innocent bystanders or 'weaker' people."],
["/pmwiki/pmwiki.php/Main/ChekhovsExhibit", "Chekhov's Exhibit", "A standby of all Caper films or any other action story where a museum is involved."],
["/pmwiki/pmwiki.php/Main/CigarFuseLighting", "Cigar-Fuse Lighting", "A badass uses his cigar to light the fuse on a stick of dynamite."],
["/pmwiki/pmwiki.php/Main/CleanCut", "Clean Cut", "Blades slice clean through bodies and other things with no jagged edges or thick wounds and can slice any body part easily."],
["/pmwiki/pmwiki.php/Main/ClifftopCaterwauling", "Clifftop Caterwauling", "A creature character hero villain... stands at the edge of a cliff and lets loose a roar to the heavens."],
["/pmwiki/pmwiki.php/Main/ClimbSlipHangClimb", "Climb Slip Hang Climb", "The hero has to climb a surface that really isn't cooperating."],
["/pmwiki/pmwiki.php/Main/ClimbingTheCliffsOfInsanity", "Climbing the Cliffs of Insanity", "Where the hero must climb an insanely tall cliff to proceed."],
["/pmwiki/pmwiki.php/Main/ClipboardOfAuthority", "Clipboard of Authority", "The hero can get in anywhere if he only holds one."],
["/pmwiki/pmwiki.php/Main/CloakAndDagger", "Cloak & Dagger", "A fictional spy agency full of glamorous secret agents which has no relationship to real-life agencies."],
["/pmwiki/pmwiki.php/Main/CobwebJungle", "Cobweb Jungle", "Any subterranean area will be full of curtains of spider webs."],
["/pmwiki/pmwiki.php/Main/ColdBloodedTorture", "Cold-Blooded Torture", "The hero is currently captured by the villains and tortured."],
["/pmwiki/pmwiki.php/Main/ColossusClimb", "Colossus Climb", "The smaller character attacks the bigger character by climbing his body to attack a vulnerable spot."],
["/pmwiki/pmwiki.php/Main/CommieNazis", "Commie Nazis", "When Fascists and Communists are conflated into one big oppressive mass."],
["/pmwiki/pmwiki.php/Main/ConcertClimax", "Concert Climax", "When the climax of the work takes place around some big public event such as a concert performance sporting event etc."],
["/pmwiki/pmwiki.php/Main/ConspicuousTrenchcoat", "Conspicuous Trenchcoat", "An 'evil' or out-of-the-ordinary character can always be identified by his concealing trenchcoat fedora and occasionally dark glasses."],
["/pmwiki/pmwiki.php/Main/ContractOnTheHitman", "Contract on the Hitman", "A professional killer suddenly finds himself being hunted by the very organization he works for."],
["/pmwiki/pmwiki.php/Main/ConvenientCranny", "Convenient Cranny", "The heroes need to hide from something. That's why they happen to stumble upon a hidden space."],
["/pmwiki/pmwiki.php/Main/ConvenientEnemyBase", "Convenient Enemy Base", "If the heroes crash-land or shipwreck while on a mission against a powerful enemy they will almost always wash up very close to that enemy's hidden headquarters."],
["/pmwiki/pmwiki.php/Main/ConvenientEscapeBoat", "Convenient Escape Boat", "When escaping anywhere near a body of water there will be a boat leaving the harbour the heroes can jump onto"],
["/pmwiki/pmwiki.php/Main/ConvenientlyPlacedSharpThing", "Conveniently-Placed Sharp Thing", "Whenever someone is tied up the bad guys always tend to leave something sharp in the room that the victim can use to cut herself free."],
["/pmwiki/pmwiki.php/Main/ConvenientlyTimedAttackFromBehind", "Conveniently Timed Attack from Behind", "The hero is helpless and about to be killed when the bad guy is taken out by an attack from behind just in time."],
["/pmwiki/pmwiki.php/Main/ConvenientlyTimedGuard", "Conveniently Timed Guard", "The heroes have just finished their infiltration but on their way out a guard sees them and sounds the alarm."],
["/pmwiki/pmwiki.php/Main/CoolAndUnusualPunishment", "Cool and Unusual Punishment", "Where the hero is tortured via some ridiculous method like tickling or opera music."],
["/pmwiki/pmwiki.php/Main/CuffsOffRubWrists", "Cuffs Off Rub Wrists", "Luckily only mild discomfort remains."],
["/pmwiki/pmwiki.php/Main/CurbStompBattle", "Curb-Stomp Battle", "An epic one-sided ass-kicking where the kicked doesn't stand a chance."],
["/pmwiki/pmwiki.php/Main/CurbstompCushion", "Curb-Stomp Cushion", "The single thing that sweetens the defeat in an epic one-sided ass-kicking somewhat."],
["/pmwiki/pmwiki.php/Main/CyanidePill", "Cyanide Pill", "Given to secret agents in case they're ever captured."],
["/pmwiki/pmwiki.php/Main/CycleOfRevenge", "Cycle of Revenge", "After you get your revenge your target's friends and family will vow revenge on you... and the cycle continues."],
["/pmwiki/pmwiki.php/Main/DangerouslyCloseShave", "Dangerously Close Shave", "Where the barber ends up cutting your throat with his razor (or almost doing so)."],
["/pmwiki/pmwiki.php/Main/DareToBeBadass", "Dare to Be Badass", "The Hero is called upon to step up to the plate and be awesome."],
["/pmwiki/pmwiki.php/Main/DarkenedBuildingShootout", "Darkened Building Shootout", "A classic denouement - the hero and villain have a shootout in a darkened building with a suitably suspenseful final shot."],
["/pmwiki/pmwiki.php/Main/TheDayOfReckoning", "The Day of Reckoning", "The day when all the prophecies and plans come to a head in a massive final confrontation."],
["/pmwiki/pmwiki.php/Main/DeadFootLeadfoot", "Dead Foot Leadfoot", "The driver of a vehicle is killed; immediately his foot gets stuck on the gas pedal causing the car to speed out of control."],
["/pmwiki/pmwiki.php/Main/DeadMansSwitch", "Dead Man's Switch", "A backup plan in case of untimely death or incapacitation used as a threat to protect the holder."],
["/pmwiki/pmwiki.php/Main/DeadMansTriggerFinger", "Dead Man's Trigger Finger", "A character wildly fires a burst of ammunition immediately after being shot."],
["/pmwiki/pmwiki.php/Main/DeadlyGas", "Deadly Gas", "Here's a hint: Don't get hit by it."],
["/pmwiki/pmwiki.php/Main/DeathCourse", "Death Course", "A gauntlet filled with enemies and/or booby traps that the hero character has to pass through."],
["/pmwiki/pmwiki.php/Main/DecoyHidingPlace", "Decoy Hiding Place", "An obvious hiding place is made visible to the pursuer while the pursued actually escapes via some other means."],
["/pmwiki/pmwiki.php/Main/DeepCoverAgent", "Deep Cover Agent", "Someone who lives a perfectly normal life for a long time all the while being a mole or spy for another government or organization."],
["/pmwiki/pmwiki.php/Main/DefconFive", "Defcon Five", "Used to refer to the highest state of alert (it's actually the lowest stage)."],
["/pmwiki/pmwiki.php/Main/DeliveryGuyInfiltration", "Delivery Guy Infiltration", "If you want to get into the enemy base just pose as a delivery guy."],
["/pmwiki/pmwiki.php/Main/DenOfIniquity", "Den of Iniquity", "A room in the Evil Overlord's lair where the mooks go to indulge their debauched pleasures."],
["/pmwiki/pmwiki.php/Main/DesperateObjectCatch", "Desperate Object", "Catch All will be lost if a falling object isn't caught in time."],
["/pmwiki/pmwiki.php/Main/DiagnosisFromDrBadass", "Diagnosis from Dr. Badass", "When the character gives a detailed accounting of how he's hurt or is hurting another."],
["/pmwiki/pmwiki.php/Main/DinerBrawl", "Diner Brawl", "The characters find themselves getting into a fight in a Greasy Spoon."],
["/pmwiki/pmwiki.php/Main/DirtForcefield", "Dirt Forcefield", "The conspicuous lack of grime dirt or bruises on actors especially those in action sequences."],
["/pmwiki/pmwiki.php/Main/DisguisedHostageGambit", "Disguised Hostage Gambit", "The villain disguises hostages as bad guys to trick The Cavalry into shooting them."],
["/pmwiki/pmwiki.php/Main/DishDash", "Dish Dash", "A character has to dash madly around a room catching stacks of falling breakable items before they hit the floor and smash."],
["/pmwiki/pmwiki.php/Main/DisneyDeath", "Disney Death", "The hero appears to have suffered a fatal wound during the final battle only to get up a few moments later. VERY common in family action movies."],
["/pmwiki/pmwiki.php/Main/DitchTheBodyguards", "Ditch the Bodyguards", "How else are you going to have a proper adventure?"],
["/pmwiki/pmwiki.php/Main/DogPileOfDoom", "Dog Pile of Doom", "Where large numbers of mooks bring you down by jumping on top of you and physically dragging you to the ground."],
["/pmwiki/pmwiki.php/Main/DoorOfDoom", "Door of Doom", "It's a very imposing door you just know it's not just a collection of knobs and hinges and going through is a Big Decision."],
["/pmwiki/pmwiki.php/Main/DragonsUpTheYinYang", "Dragons Up the Yin Yang", "Any work featuring martial arts or Eastern mysticism will have either an Eastern dragon or a Yin/Yang symbol somewhere."],
["/pmwiki/pmwiki.php/Main/DramaBombFinale", "Drama Bomb Finale", "An otherwise comedic story trying its hand at a dramatic moment near the show's last episode or two totally out of left field."],
["/pmwiki/pmwiki.php/Main/DressingAsTheEnemy", "Dressing as the Enemy", "Where the hero dresses up in a face-concealing suit of armor stolen from the enemy to infiltrate their base."],
["/pmwiki/pmwiki.php/Main/DroolHello", "*Drool* Hello", "The first inkling that a monster is above you? That yucky liquid splashing over your shoulders..."],
["/pmwiki/pmwiki.php/Main/DungeonBypass", "Dungeon Bypass", "Where heroes just blast through or over that complicated maze or trial that the villain has set up rather than actually solving it."],
["/pmwiki/pmwiki.php/Main/DungeonCrawling", "Dungeon Crawling", "The act of exploring a dungeon while looking for treasure avoiding traps and beating off monsters."],
["/pmwiki/pmwiki.php/Main/DurableDeathtrap", "Durable Deathtrap", "The ruins are ancient but damn if those giant guillotine blades aren't as sharp as the day they were made!"],
["/pmwiki/pmwiki.php/Main/DyeOrDie", "Dye or Die", "Where a secret agent has to dye his or her hair to avoid detection."],
["/pmwiki/pmwiki.php/Main/EducationThroughPyrotechnics", "Education Through Pyrotechnics", "There's no better way to make a lesson stick than by adding explosions."],
["/pmwiki/pmwiki.php/Main/EjectionSeat", "Ejection Seat", "Try not to push that button accidentally."],
["/pmwiki/pmwiki.php/Main/ElevatorEscape", "Elevator Escape", "The best way to flee The Mafia."],
["/pmwiki/pmwiki.php/Main/EmergencyCargoDump", "Emergency Cargo Dump", "Throwing cargo out to avoid crashing or to outrace the bad guys."],
["/pmwiki/pmwiki.php/Main/EmergencyStash", "Emergency Stash", "How our hero manages to get money IDs and weapons while on the run."],
["/pmwiki/pmwiki.php/Main/EmptyElevator", "Empty Elevator", "Will the hero/villain/monster be in the elevator when it opens? Of course not! He/she/it is hiding somewhere nearby ready to kick ass."],
["/pmwiki/pmwiki.php/Main/EmptyQuiver", "Empty Quiver", "When a nuclear bomb shows up in a story it'll inevitably end up in the hands of the bad guys."],
["/pmwiki/pmwiki.php/Main/EnemyRisingBehind", "Enemy Rising Behind", "Some one (or some thing) hostile is coming into view from behind and below."],
["/pmwiki/pmwiki.php/Main/EverybodyWasKungFuFighting", "Everybody Was Kung-Fu Fighting", "Everybody knows kung fu and uses it often and awesomely and I mean everyone."],
["/pmwiki/pmwiki.php/Main/EveryoneChasingYou", "Everyone Chasing You", "A character is chased by a whole bunch of other characters."],
["/pmwiki/pmwiki.php/Main/ExtremelyShortTimespan", "Extremely Short Timespan", "When the events of a whole story (novel arc movie etc.) takes place in a short period of time. Usually three days or less."],
["/pmwiki/pmwiki.php/Main/ExoticWeaponSupremacy", "Exotic Weapon Supremacy", "If a character uses an unusual weapon that indicates that they're more badass than everyone else."],
["/pmwiki/pmwiki.php/Main/ExplodingFishTanks", "Exploding Fish Tanks", "If an aquarium is shown at any point the aquarium will inevitably be destroyed."],
["/pmwiki/pmwiki.php/Main/ExplosiveLeash", "Explosive Leash", "Where a bomb is attached to a prisoner while they carry out a dangerous mission."],
["/pmwiki/pmwiki.php/Main/ExpositionDiagram", "Exposition Diagram", "A diagram is set up to explain the upcoming plan."],
["/pmwiki/pmwiki.php/Main/FacingTheBulletsOneLiner", "Facing the Bullets One-Liner", "He's about to die but he's got time for one last quip."],
["/pmwiki/pmwiki.php/Main/FastRoping", "Fast-Roping", "Where the heroes come onto the scene by rappelling down from above."],
["/pmwiki/pmwiki.php/Main/FedToTheBeast", "Fed to the Beast", "A very common Death Trap common for both Human Sacrifice and villainous disposal needs alike."],
["/pmwiki/pmwiki.php/Main/FerrisWheelOfDoom", "Ferris Wheel of Doom", "When you see a Ferris wheel it's either going to start collapsing or break free and start rolling away."],
["/pmwiki/pmwiki.php/Main/FightMagnet", "Fight Magnet", "Wherever the hero goes someone always wants a piece of him."],
["/pmwiki/pmwiki.php/Main/FighterLaunchingSequence", "Fighter-Launching Sequence", "Seeing planes space fighters and other similar vehicles take off into battle."],
["/pmwiki/pmwiki.php/Main/FinalBattle", "Final Battle", "The big lavish fight scene and climax to the story."],
["/pmwiki/pmwiki.php/Main/FlamethrowerBackfire", "Flamethrower Backfire", "What's the best way to beat a guy with a flamethrower? Blow up his fuel tank!"],
["/pmwiki/pmwiki.php/Main/FlamingEmblem", "Flaming Emblem", "Have an Iconic Logo? Make a big fire shaped like it."],
["/pmwiki/pmwiki.php/Main/Flynning", "Flynning", "The classic swordplay of swashbuckling movies."],
["/pmwiki/pmwiki.php/Main/FoeTossingCharge", "Foe-Tossing Charge", "Where a character barrels toward a target and tosses away anyone who gets in the way without a glance."],
["/pmwiki/pmwiki.php/Main/ForcedPrizeFight", "Forced Prize Fight", "Combatants are forced by the 'powers that be' to brawl box or otherwise fight. Sometimes to the death."],
["/pmwiki/pmwiki.php/Main/ForgingScene", "Forging Scene", "A scene dedicated to forging a kickass weapon or something."],
["/pmwiki/pmwiki.php/Main/FriendToAllChildren", "Friend to All Children", "A gentle character is fond of children."],
["/pmwiki/pmwiki.php/Main/FutileHandReach", "Futile Hand Reach", "When something bad happens to a character the protagonist will reach out towards the character in question."],
["/pmwiki/pmwiki.php/Main/GenericCopBadges", "Generic Cop Badges", "Badges and car decals in many cop shows are generic with just the word 'Police'."],
["/pmwiki/pmwiki.php/Main/GenocideDilemma", "Genocide Dilemma", "Where an entire planet of people is out to destroy Earth - do we get them first?"],
["/pmwiki/pmwiki.php/Main/GiantFootOfStomping", "Giant Foot of Stomping", "A big foot comes out of nowhere and stomps someone to death."],
["/pmwiki/pmwiki.php/Main/GivingTheSwordToANoob", "Giving the Sword to a Noob", "A moron is trusted with a vital weapon or device and tries to use it instead of giving it to the right person."],
["/pmwiki/pmwiki.php/Main/GladiatorGames", "Gladiator Games", "Where people have to fight each other or monsters to the death while lots of people look on and cheer."],
["/pmwiki/pmwiki.php/Main/GladiatorRevolt", "Gladiator Revolt", "Where the hero captured as a gladiator starts a rebellion with the gladiators breaking out of the slave pits."],
["/pmwiki/pmwiki.php/Main/GogglesDoSomethingUnusual", "Goggles Do Something Unusual", "Eyewear that does something other than what their mundane design purpose is."],
["/pmwiki/pmwiki.php/Main/GotVolunteered", "Got Volunteered", "When a character is dragooned into a dangerous job against their will."],
["/pmwiki/pmwiki.php/Main/GovernmentAgencyOfFiction", "Government Agency of Fiction", "Either a fictional government agency or a real one described in a fictional way."],
["/pmwiki/pmwiki.php/Main/GraveRobbing", "Grave Robbing", "Because dead bodies are always useful For SCIENCE!"],
["/pmwiki/pmwiki.php/Main/GreatEscape", "Great Escape", "Breaking out of prison."],
["/pmwiki/pmwiki.php/Main/GunpointBanter", "Gunpoint Banter", "When two characters have their guns aimed at one another ready to shoot but decide to have a conversation instead."],
["/pmwiki/pmwiki.php/Main/HallwayFight", "Hallway Fight", "Characters fight their way down the length of a hallway."],
["/pmwiki/pmwiki.php/Main/HandsOffMyFluffy", "Hands Off My Fluffy!", "Where the heroes attack a monster who looks like it's accosting a girl when it turns out the monster is the girl's pet."],
["/pmwiki/pmwiki.php/Main/HarmlessFreezing", "Harmless Freezing", "A character is frozen solid and then unfreezes with no adverse effects."],
["/pmwiki/pmwiki.php/Main/HassleFreeHotwire", "Hassle-Free Hotwire", "Anybody can hotwire a car: just open a random cover grab two wires and stick them together!"],
["/pmwiki/pmwiki.php/Main/HeroStoleMyBike", "Hero Stole My Bike", "A hero in a hurry grabs somebody else's car or bike to aid in his chase scene."],
["/pmwiki/pmwiki.php/Main/HeroesRUs", "Heroes 'R' Us", "A large philanthropic organization whose 'job' is as close as anyone can tell to fund heroes."],
["/pmwiki/pmwiki.php/Main/HeroesUnlimited", "Heroes Unlimited", "A Story Arc or season which features an expansion of the general cast."],
["/pmwiki/pmwiki.php/Main/HeroicBSOD", "Heroic B.S.O.D.", "An earth-shattering revelation or horrible event affects the hero leaving him either mentally shut down out of shock or subject to a violent outburst."],
["/pmwiki/pmwiki.php/Main/HeroicSafeMode", "Heroic Safe Mode", "An earth-shattering revelation or horrible event affects the hero causing him to flee or fight as an automatic response."],
["/pmwiki/pmwiki.php/Main/HeyCatch", "Hey Catch!", "A character who throws something to another character to make him catch it often to distract him."],
["/pmwiki/pmwiki.php/Main/HeyWait", "Hey Wait!", "In the heart of enemy territory the hero narrowly escapes detection when they're told something like 'your shoe is untied'."],
["/pmwiki/pmwiki.php/Main/HeyYouHaymaker", "Hey You! Haymaker", "Tap your opponent on the back and when he turns around punch him in the face."],
["/pmwiki/pmwiki.php/Main/HighDiveEscape", "High-Dive Escape", "The hero or villain escapes pursuers by making a seemingly-suicidal jump off something very high."],
["/pmwiki/pmwiki.php/Main/HitchhikerHeroes", "Hitchhiker Heroes", "A band of warriors or (more commonly) would-be warriors who join up with The Hero over the course of his journey."],
["/pmwiki/pmwiki.php/Main/HollywoodAcid", "Hollywood Acid", "Acid in Hollywood movies does not act exactly like real acid would and is often much more dangerous."],
["/pmwiki/pmwiki.php/Main/HollywoodCB", "Hollywood CB", "The radios always work perfectly you talk only to the person you're addressing and you can interrupt people. Especially the bad guys."],
["/pmwiki/pmwiki.php/Main/HollywoodFire", "Hollywood Fire", "Fire in Hollywood movies does not act exactly like real fire would and is not quite as dangerous."],
["/pmwiki/pmwiki.php/Main/HollywoodHealing", "Hollywood Healing", "No matter how badly he's injured the hero never ends up with permanent scars."],
["/pmwiki/pmwiki.php/Main/HollywoodNatives", "Hollywood Natives", "Someone has to live in wherever it is the protagonists are visiting."],
["/pmwiki/pmwiki.php/Main/HonorAmongThieves", "Honor Among Thieves", "Thieves turn out to be remarkably honorable fellows in fiction especially amongst other thieves."],
["/pmwiki/pmwiki.php/Main/HopeSpot", "Hope Spot", "A glimmer of hope for the hero which is quickly dashed."],
["/pmwiki/pmwiki.php/Main/HowDoIShotWeb", "How Do I Shot Web?", "Where a character has to figure out how to use his newly-obtained superpowers."],
["/pmwiki/pmwiki.php/Main/HumanChess", "Human Chess", "Chess played where the pieces are actual people... sometimes to the death."],
["/pmwiki/pmwiki.php/Main/HuntingTheMostDangerousGame", "Hunting the Most Dangerous Game", "Where the villains formally hunt the heroes."],
["/pmwiki/pmwiki.php/Main/IKnowMortalKombat", "I Know Mortal Kombat", "A character acquires a needed skill not by ever actually learning that skill but by playing a video game which simulated that skill."],
["/pmwiki/pmwiki.php/Main/INeedNoLadders", "I Need No Ladders", "Where a character decides to screw taking the stairs because everything's better with epic jumps."],
["/pmwiki/pmwiki.php/Main/INeedYouStronger", "I Need You Stronger", "The Big Bad lets the heroes continue on their quest despite being more than capable of wiping them out because they're not strong enough to suit his purposes yet."],
["/pmwiki/pmwiki.php/Main/IfYoureSoEvilEatThisKitten", "If You're So Evil Eat This Kitten", "The Bad Guys challenge someone (usually the hero pretending to be a Bad Guy) to do something evil to prove his evilness."],
["/pmwiki/pmwiki.php/Main/ImminentDangerClue", "Imminent Danger Clue", "A seemingly mundane detail of the setting indicates that a character has just walked into a trap; the danger will come into play shortly after the character realizes it exists."],
["/pmwiki/pmwiki.php/Main/ImplausibleFencingPowers", "Implausible Fencing Powers", "Where swordsmen can do insane things with their swords like deflecting bullets or cutting clothes to pieces without touching skin."],
["/pmwiki/pmwiki.php/Main/ImpossibleMissionCollapse", "Impossible Mission Collapse", "An elaborate high-risk plan is concocted by the good guys we hear all the planning and then it never gets past step one."],
["/pmwiki/pmwiki.php/Main/ImpressivePyrotechnics", "Impressive Pyrotechnics", "Explosions always look the same even when the materials combusting shouldn't explode that way."],
["/pmwiki/pmwiki.php/Main/ImprobableCover", "Improbable Cover", "When a character leaps behind something to escape an explosion ducks to avoid a rolling wall of flame or closes a door on an avalanche."],
["/pmwiki/pmwiki.php/Main/ImprobableInfantSurvival", "Improbable Infant Survival", "Even the worst villains are not allowed to kill children or infants."],
["/pmwiki/pmwiki.php/Main/ImprovisedParachute", "Improvised Parachute", "What a character uses to slow a great fall when a real parachute is not available."],
["/pmwiki/pmwiki.php/Main/ImprovisedZipline", "Improvised Zipline", "When a character really needs to rappel down a building but doesn't have a rope he'll improvise one."],
["/pmwiki/pmwiki.php/Main/IndyEscape", "Indy Escape", "The character is chased down a tunnel by something very large clich?y a boulder or a giant monster."],
["/pmwiki/pmwiki.php/Main/IndyHatRoll", "Indy Hat Roll", "A character makes his way under a vertically closing door Just in Time by rolling under it."],
["/pmwiki/pmwiki.php/Main/IndyPloy", "Indy Ploy", "There is no plan. The hero is just plain winging it."],
["/pmwiki/pmwiki.php/Main/IneffectualDeathThreats", "Ineffectual Death Threats", "Characters make death threats that they never seem to carry out."],
["/pmwiki/pmwiki.php/Main/InevitableWaterfall", "Inevitable Waterfall", "If a character is drifting on a raft or log along a river they will fall down a waterfall. No exceptions."],
["/pmwiki/pmwiki.php/Main/InnocuouslyImportantEpisode", "Innocuously Important Episode", "A seemingly weak episode early in a Story Arc that subtly sets events in motion that lead to a big payoff later on.",],
["/pmwiki/pmwiki.php/Main/InstantKnots", "Instant Knots", "Where heroes can make a rope whip chain or Grappling-Hook Pistol wrap itself around a distant object securely."],
["/pmwiki/pmwiki.php/Main/InstrumentOfMurder", "Instrument of Murder", "A character who has a musical instrument that doubles as a deadly weapon."],
["/pmwiki/pmwiki.php/Main/InvoluntaryGroupSplit", "Involuntary Group Split", "The destruction of a structure separates the characters from each other."],
["/pmwiki/pmwiki.php/Main/IsleOfGiantHorrors", "Isle of Giant Horrors", "Being trapped on an island inhabited by giant monsters."],
["/pmwiki/pmwiki.php/Main/JuggleFu", "Juggle Fu", "Someone can throw an object in the air perform some action sequence while it is airborne then catch it on its way down."],
["/pmwiki/pmwiki.php/Main/JustAKid", "Just a Kid", "The young hero meets a series of dismissive characters who assume ineptness because (wait for it)? You're just a kid."],
["/pmwiki/pmwiki.php/Main/JustBetweenYouAndMe", "Just Between You and Me", "Villains will pause to give a monologue to the heroes detailing their entire plot."],
["/pmwiki/pmwiki.php/Main/KatanasAreJustBetter", "Katanas Are Just Better", "I slice you! Hiii-yaa!"],
["/pmwiki/pmwiki.php/Main/KeepAway", "Keep Away", "The game of tossing an object around in a group to keep it away from someone else."],
["/pmwiki/pmwiki.php/Main/KillSteal", "Kill Steal", "Taking a kill someone else was about to make."],
["/pmwiki/pmwiki.php/Main/KindaBusyHere", "Kinda Busy Here", "When a cell phone rings at an inconvenient time like when you're in a gunfight."],
["/pmwiki/pmwiki.php/Main/KitchenChase", "Kitchen Chase", "The hero runs though a kitchen to escape the bad guys."],
["/pmwiki/pmwiki.php/Main/LastBreathBullet", "Last Breath Bullet", "The bad guys have been defeated but one of them pulls off a shot with their last breath often killing one of the heroes before dying."],
["/pmwiki/pmwiki.php/Main/LastVillainStand", "Last Villain Stand", "The main bad guy decides to take a one man stand against the heroes when he's got no one left to fight for him."],
["/pmwiki/pmwiki.php/Main/LatexPerfection", "Latex Perfection", "A latex mask so perfect that it is impossible to tell the wearer from the person he is impersonating until the moment he pulls off his face."],
["/pmwiki/pmwiki.php/Main/LawEnforcementInc", "Law Enforcement Inc.", "A self-funded self-supporting private agency which can act as a legal authority and law enforcement power or as an official military outfit."],
["/pmwiki/pmwiki.php/Main/LetsDance", "Let's Dance", "A common Pre Ass Kicking One Liner."],
["/pmwiki/pmwiki.php/Main/LetsFightLikeGentlemen", "Let's Fight Like Gentlemen", "No matter how much they hate each other the two opponents will stick by the rules in their fight."],
["/pmwiki/pmwiki.php/Main/LetsGetDangerous", "Let's Get Dangerous!", "A moment in the story when the quirky eccentric supporting cast stop being quirky and eccentric and start demonstrating why you should respect your elders."],
["/pmwiki/pmwiki.php/Main/LetsGetOutOfHere", "Let's Get Out of Here", "Time to bid a hasty retreat!"],
["/pmwiki/pmwiki.php/Main/LetsYouAndHimFight", "Let's You and Him Fight", "Where two heroes fight each other under mistaken pretenses."],
["/pmwiki/pmwiki.php/Main/LifeOrLimbDecision", "Life-or-Limb Decision", "When a person is forced to make a terrible choice ? they need to remove one of their appendages in order to escape with their life."],
["/pmwiki/pmwiki.php/Main/LightheartedRematch", "Lighthearted Rematch", "Two heroes have fought each other for real stakes. When the story's over they smile and have a rematch for fun's sake."],
["/pmwiki/pmwiki.php/Main/LineInTheSand", "Line in the Sand", "Where a military leader offers his recruits a choice to stay and fight or flee (they usually stay)."],
["/pmwiki/pmwiki.php/Main/LittleHeroBigWar", "Little Hero Big War", "Where the fantasy hero is off having adventures while a war is going on in the background."],
["/pmwiki/pmwiki.php/Main/LittleStowaway", "Little Stowaway Children", "secretly following the more serious heroes on their adventure."],
["/pmwiki/pmwiki.php/Main/LiveActionEscortMission", "Live-Action Escort Mission", "Where the heroes have to get someone (often a spoiled kid) from one place to another and have to deal with his/her antics along the way."],
["/pmwiki/pmwiki.php/Main/LockingMacGyverInTheStoreCupboard", "Locking MacGyver In The Store Cupboard", "When good guys get locked in a cell all of the equipment that they need to escape is in the cell with them."],
["/pmwiki/pmwiki.php/Main/LoserHasYourBack", "Loser Has Your Back", "In an action scene the last person alive other than the hero is the last person you'd expect."],
["/pmwiki/pmwiki.php/Main/MagneticHero", "Magnetic Hero", "A hero with such personal magnetism that he is capable of persuading others to join him in his quest."],
["/pmwiki/pmwiki.php/Main/MakeRoomForTheNewPlot", "Make Room for the New Plot", "When one important plot element is abruptly resolved so that the characters can combat a more immediate dangerous conflict instead."],
["/pmwiki/pmwiki.php/Main/TheManIsKeepingUsDown", "The Man Is Keeping Us Down", "The heroes have almost won but end up failing due to factors outside their control often societal in nature."],
["/pmwiki/pmwiki.php/Main/ManOnFire", "Man on Fire", "Aaaaahhhhh! I'm on fire!"],
["/pmwiki/pmwiki.php/Main/Mangst", "Mangst", "Quiet internal angsting done by real men and badasses."],
["/pmwiki/pmwiki.php/Main/MarkedBullet", "Marked Bullet", "A bullet with special markings or words on it. Often the name of someone a character wants dead."],
["/pmwiki/pmwiki.php/Main/MatchlightDangerRevelation", "Matchlight Danger Revelation", "Two animated characters are in pitch-black darkness; one strikes a match revealing they are in an incredibly dangerous place or situation."],
["/pmwiki/pmwiki.php/Main/MaximumFunChamber", "Maximum Fun Chamber", "An unspecified threat so awful that mere mention of it makes the strong go pale and the weak-hearted clutch their chest."],
["/pmwiki/pmwiki.php/Main/TheMeddlingKidsAreUseless", "The Meddling Kids Are Useless", "The heroes get into a lot of danger and excitement but in the end they don't actually stop the villain or accomplish anything directly."],
["/pmwiki/pmwiki.php/Main/MenacingStroll", "Menacing Stroll", "The lithe athletic walk of the perennial badass."],
["/pmwiki/pmwiki.php/Main/MexicanStandoff", "Mexican Standoff", "A stalemate where everyone has a weapon pointed at them."],
["/pmwiki/pmwiki.php/Main/MidairRepair", "Midair Repair", "Where a malfunctioning falling aircraft can be fixed by the mechanic in midair before it hits the ground."],
["/pmwiki/pmwiki.php/Main/MinionMaracas", "Minion Maracas", "When somebody who would not otherwise be expected to raise somebody else off the ground does so under the influence of a strong emotion and shakes them in mid-air to mark their point."],
["/pmwiki/pmwiki.php/Main/MisfitMobilizationMoment", "Misfit Mobilization Moment", "When a dysfunctional group of losers transforms into a well-oiled machine."],
["/pmwiki/pmwiki.php/Main/MissionBriefing", "Mission Briefing", "The briefing before a mission of whatever form."],
["/pmwiki/pmwiki.php/Main/MistakenForBadass", "Mistaken for Badass", "A bumbling perfectly normal Nice Guy who gets mixed up in something dangerous and by sheer luck does the sort of things that convinces everyone he must be insanely badass."],
["/pmwiki/pmwiki.php/Main/MistakenForSpies", "Mistaken for Spies", "When the heroes arrive in a town just as something nasty happens they will inevitably be accused of it and thrown in jail."],
["/pmwiki/pmwiki.php/Main/MonumentalBattle", "Monumental Battle", "Somehow a disproportionate number of fictional fights break out at easily-recognized national monuments and landmarks around the world."],
["/pmwiki/pmwiki.php/Main/MonumentalDamage", "Monumental Damage", "Where villains or aliens attack major landmarks."],
["/pmwiki/pmwiki.php/Main/MonumentalDamageResistance", "Monumental Damage Resistance", "Where the villains or aliens attacking the major landmarks leave some landmarks standing."],
["/pmwiki/pmwiki.php/Main/MostDefinitelyNotAccompanyingUs", "Most Definitely Not Accompanying Us", "Said to any younger or inexperienced members of the group before the older experienced members head to where the action is"],
["/pmwiki/pmwiki.php/Main/MuckingInTheMud", "Mucking in the Mud", "You know that when you see a mudpit or a mud bog you can go through it. Just be aware that there are only a few safe spots and there are some swamps in which you can go too deep..."],
["/pmwiki/pmwiki.php/Main/MusicalTrigger", "Musical Trigger", "A specific musical cue — not in the BGM but in actual music being played by someone or something In-Universe — serves as the trigger for some event."],
["/pmwiki/pmwiki.php/Main/MustStateIfYoureACop", "Must State If You're a Cop", "When asked by a character being interrogated for whatever reason."],
["/pmwiki/pmwiki.php/Main/MyCountryRightOrWrong", "My Country Right or Wrong", "A person who may not like the policies of their country but will fight for it regardless."],
["/pmwiki/pmwiki.php/Main/MyNameIsInigoMontoya", "My Name Is Inigo Montoya", "The character announces who they are unprompted."],
["/pmwiki/pmwiki.php/Main/MyopicArchitecture", "Myopic Architecture", "The way past the door is easier than it looks."],
["/pmwiki/pmwiki.php/Main/NebulousEvilOrganisation", "Nebulous Evil Organisation", "A vast deep-pocketed machine with one apparent goal: The proliferation of evil across the globe maybe with some personal profit on the side."],
["/pmwiki/pmwiki.php/Main/NerfArm", "Nerf Arm", "Any logically less-than-lethal weapon which ends up being otherwise just as effective as its 'real' equivalent."],
["/pmwiki/pmwiki.php/Main/NeutralFemale", "Neutral Female", "When the hero and villain are fighting the Distressed Damsel will just sit there and watch or be ineffectual in what she tries to do."],
["/pmwiki/pmwiki.php/Main/NiceJobBreakingItHero", "Nice Job Breaking It Hero!", "Where a hero's actions unwittingly make the situation worse rather than better."],
["/pmwiki/pmwiki.php/Main/NiceJobFixingItVillain", "Nice Job Fixing It Villain!", "Where a villain's actions unwittingly make the situation better rather than worse."],
["/pmwiki/pmwiki.php/Main/NightVisionGoggles", "Night-Vision Goggles", "What would you use them to look at?"],
["/pmwiki/pmwiki.php/Main/NitroExpress", "Nitro Express", "Hauling unstable explosives over dangerous terrain. What could possibly go wrong?"],
["/pmwiki/pmwiki.php/Main/NoEndorHolocaust", "No Endor Holocaust", "When you blow up the giant monster/enemy base/teacup it should cause untold damage to the places around it but we never see such damage."],
["/pmwiki/pmwiki.php/Main/NoEscapeButDown", "No Escape but Down", "When faced with the choice of getting captured by pursuers or jumping from a great height chose the latter."],
["/pmwiki/pmwiki.php/Main/NoFEMAResponse", "No FEMA Response", "A disaster has struck but don't expect any incoming aid."],
["/pmwiki/pmwiki.php/Main/NoMrBondIExpectYouToDine", "No Mr. Bond I Expect You to Dine", "When the hero is captured and instead of throwing him in the dungeon the villain treats him as a guest."],
["/pmwiki/pmwiki.php/Main/NoOneGetsLeftBehind", "No One Gets Left Behind", "The hero refuses to leave a wounded or captured comrade behind."],
["/pmwiki/pmwiki.php/Main/NoOneShouldSurviveThat", "No One Should Survive That", "When a character survives a situation that should by all accounts have been lethal often through sheer luck or coincidence."],
["/pmwiki/pmwiki.php/Main/NoOSHACompliance", "No OSHA Compliance", "Bases and complexes have all kinds of insanely dangerous walkways and areas because they're cool and make for nail-biting suspense sequences."],
["/pmwiki/pmwiki.php/Main/NoPlansNoPrototypeNoBackup", "No Plans No Prototype No Backup", "Any dangerous device or technology owned by a villain is one-of-a-kind; there are no design notes no prototypes and no backup copies."],
["/pmwiki/pmwiki.php/Main/NonFatalExplosions", "Non-Fatal Explosions", "Explosions don't cause concussion damage from the shockwave or rip you up with shrapnel... they just give you a little push."],
["/pmwiki/pmwiki.php/Main/NonViolentInitialConfrontation", "Non Violent Initial Confrontation", "Sometimes you really do want to ask questions first."],
["/pmwiki/pmwiki.php/Main/NormallyIWouldBeDeadNow", "Normally I Would Be Dead Now", "Where somebody survives a blow or wound that even by Hollywood standards should have killed them and keeps fighting."],
["/pmwiki/pmwiki.php/Main/NotInThisForYourRevolution", "Not in This for Your Revolution", "A character is on a quest that could save the world but he doesn't care about that; he's only in it for personal reasons."],
["/pmwiki/pmwiki.php/Main/NotWorthKilling", "Not Worth Killing", "The averagely-skilled friends of the highly-skilled hero survive their encounter with the Big Bad or Dragon because the bad guy couldn't be bothered to finish them off."],
["/pmwiki/pmwiki.php/Main/NowItsMyTurn", "Now It's My Turn", "Where one character survives what has been built up as a nasty attack grins and unleashes a counterattack."],
["/pmwiki/pmwiki.php/Main/ANuclearError", "A Nuclear Error", "Where a work takes creative liberties regarding nuclear weapons and nuclear weapons policy."],
["/pmwiki/pmwiki.php/Main/ObstacleExposition", "Obstacle Exposition", "After having outlined the goal for the episode Mr. Exposition will describe a list of all the insurmountable obstacles that stand in the way of that goal."],
["/pmwiki/pmwiki.php/Main/AnOfferYouCantRefuse", "An Offer You Can't Refuse", "Where the bad guy forces the good guy into doing something via threats kidnapping or blackmail."],
["/pmwiki/pmwiki.php/Main/OminousWalk", "Ominous Walk", "A villain or Anti-Hero will have an enemy at their mercy and instead of immediately shooting them they'll slowly walk towards them."],
["/pmwiki/pmwiki.php/Main/OneRiotOneRanger", "One Riot One Ranger", "Where the government sends in only one man to do a job that rightfully a whole squad or army should do."],
["/pmwiki/pmwiki.php/Main/OneTrueSequence", "One True Sequence", "Where there is a set of objects or objectives to obtain the good and bad guys will always end up fighting over the same one at the same time."],
["/pmwiki/pmwiki.php/Main/OnlyICanKillHim", "Only I Can Kill Him", "Rule of Drama: Only the main character can kill the Big Bad. Anyone else who tries will be curb stomped."],
["/pmwiki/pmwiki.php/Main/TheOnlyOneAllowedToDefeatYou", "The Only One Allowed to Defeat You", "Contriving to make it all about these two guys the good guy and the bad guy."],
["/pmwiki/pmwiki.php/Main/OpenSaysMe", "Open! Says Me", "When met with an unyielding door lock one of the heroes will just blast it off or break down the door."],
["/pmwiki/pmwiki.php/Main/OptOut", "Opt Out", "Where a character decides not to take part in the climactic final battle and leaves."],
["/pmwiki/pmwiki.php/Main/OutOfCharacterAlert", "Out-of-Character Alert", "The villain has captured someone and sends a message in their name to their family or friends. However something in the message is obviously something that the capturee would never have written."],
["/pmwiki/pmwiki.php/Main/OutOfSightOutOfMind", "Out of Sight Out of Mind", "Where something is 'destroyed' by just throwing it off-screen."],
["/pmwiki/pmwiki.php/Main/OutrunTheFireball", "Outrun the Fireball", "Warning: Not recommended for those of us actually occupying real life."],
["/pmwiki/pmwiki.php/Main/OutsideRide", "Outside Ride", "Where somebody hops on the top or side of a car as it's moving."],
["/pmwiki/pmwiki.php/Main/PackedHero", "Packed Hero", "A Conveyor Belt o'doom run results in the hero passing out the other end as a package."],
["/pmwiki/pmwiki.php/Main/PaperThinDisguise", "Paper-Thin Disguise", "An extremely transparent disguise that anybody in their right mind could see through yet the on-screen characters can't."],
["/pmwiki/pmwiki.php/Main/LeParkour", "Le Parkour", "A discipline which emphasizes getting from point A to point B in a straight line even if that line goes around under or over obstacles. It's also really cool."],
["/pmwiki/pmwiki.php/Main/PassingTheTorch", "Passing the Torch", "The Hero formally hands over his heroing business to a new guy."],
["/pmwiki/pmwiki.php/Main/PayingForTheActionScene", "Paying for the Action Scene", "A character gets into a fight in a private establishment and pays for the mess he/she left behind."],
["/pmwiki/pmwiki.php/Main/PercussivePrevention", "Percussive Prevention", "Stopping someone from doing something stupid by knocking them out and then doing it yourself."],
["/pmwiki/pmwiki.php/Main/PGExplosives", "PG Explosives", "When something explodes the violence remains but all the blood and gore is removed."],
["/pmwiki/pmwiki.php/Main/PinPullingTeeth", "Pin-Pulling Teeth", "Few things are more badass than using your teeth to yank the pin from a grenade before tossing."],
["/pmwiki/pmwiki.php/Main/PitTrap", "Pit Trap", "A hole in the ground that's somehow covered up so as to blend in with the surrounding terrain."],
["/pmwiki/pmwiki.php/Main/PluckyMiddie", "Plucky Middie", "A protagonist in a story set aboard a sailing ship who's a young brave teenager sailing into adventure."],
["/pmwiki/pmwiki.php/Main/PlummetPerspective", "Plummet Perspective", "It's a long way down if the hero falls."],
["/pmwiki/pmwiki.php/Main/PowderTrail", "Powder Trail", "A trail of gunpowder left on the ground as a makeshift fuse to blow up stuff."],
["/pmwiki/pmwiki.php/Main/PreAsskickingMutter", "Pre-Ass-Kicking Mutter", "Villain got you by the throat? Just try to say something they'll ease up so you can clarify and kick their ass!"],
["/pmwiki/pmwiki.php/Main/ThePrecariousLedge", "The Precarious Ledge", "A character moves along a very high ledge to get from point A to point B."],
["/pmwiki/pmwiki.php/Main/ThePreciousPreciousCar", "The Precious Precious Car", "A jerk has a car which he loves and absolutely refuses to let anyone touch. It will either be stolen destroyed or both."],
["/pmwiki/pmwiki.php/Main/ProtectThisHouse", "Protect This House", "The hero's home comes under attack."],
["/pmwiki/pmwiki.php/Main/ProtectedByAChild", "Protected by a Child", "Where the hero can't get to the villain to administer smackdown because a child is in the way protecting him."],
["/pmwiki/pmwiki.php/Main/Protectorate", "Protectorate", "A specific person place or thing or set thereof which our hero is responsible for defending."],
["/pmwiki/pmwiki.php/Main/PunchPunchPunchUhOh", "Punch! Punch! Punch! Uh Oh...", "In a fistfight one character delivers a set of rapid-fire punches into the other one's gut only to have him smile and start delivering serious violence."],
["/pmwiki/pmwiki.php/Main/PunchedAcrossTheRoom", "Punched Across the Room", "In movies and videogames punches and kicks send you flying usually in the direction of something breakable."],
["/pmwiki/pmwiki.php/Main/PunctuatedPounding", "Punctuated Pounding", "It's for YOU! [wham!] You shouldn't [wham!] hurt [wham!] people! [wham!]"],
["/pmwiki/pmwiki.php/Main/ThePurge", "The Purge", "When a villain takes over a big company or government the first thing he does is start ordering the deaths of quite a lot of people."],
["/pmwiki/pmwiki.php/Main/QuicksandSucks", "Quicksand Sucks", "Dip a toe into quicksand and suddenly you get sucked down to the bowels of the earth!"],
["/pmwiki/pmwiki.php/Main/TheRadioDiesFirst", "The Radio Dies First", "A two-way radio is put out of commission to allow the plot to proceed."],
["/pmwiki/pmwiki.php/Main/RailroadTracksOfDoom", "Railroad Tracks of Doom", "Any time you see railroad tracks a train will appear usually giving a character a near-death suspenseful miss."],
["/pmwiki/pmwiki.php/Main/RansackedRoom", "Ransacked Room", "You can tell it's been ransacked because the underwear is strewn over the chair instead of strewn over the floor."],
["/pmwiki/pmwiki.php/Main/RapePillageAndBurn", "Rape Pillage and Burn", "A group of bandits pirates or even mooks working for a Big Bad sack a town - looting damaging property and sometimes even murdering and kidnapping innocent townsfolk. Then they burn it down."],
["/pmwiki/pmwiki.php/Main/RatedMForManly", "Rated M for Manly", "Something soaked to the brim with testosterone and badassery. Made by men for men."],
["/pmwiki/pmwiki.php/Main/RedemptionDemotion", "Redemption Demotion", "When a bad guy becomes a good guy his power potential goes down significantly."],
["/pmwiki/pmwiki.php/Main/RedemptionPromotion", "Redemption Promotion", "When a bad guy becomes a good guy his power potential goes up significantly."],
["/pmwiki/pmwiki.php/Main/RedundantRescue", "Redundant Rescue", "Where a character is 'saved' when as it turns out he didn't really need to be."],
["/pmwiki/pmwiki.php/Main/ReedSnorkel", "Reed Snorkel", "Plucking a hollow reed and using it to breathe while underwater."],
["/pmwiki/pmwiki.php/Main/RemovingTheEarpiece", "Removing the Earpiece", "When an agent or operative removes their communication earpiece they're going to disobey an order go rogue or say something 'off the record.'"],
["/pmwiki/pmwiki.php/Main/ResignationsNotAccepted", "Resignations Not Accepted", "The only way to leave an evil organization is death."],
["/pmwiki/pmwiki.php/Main/TheRestShallPass", "The Rest Shall Pass", "When the heroic team is split up by the sudden arrival of a series of villains."],
["/pmwiki/pmwiki.php/Main/RevolversAreJustBetter", "Revolvers Are Just Better", "They're just COOL dammit!"],
["/pmwiki/pmwiki.php/Main/RightUnderTheirNoses", "Right Under Their Noses", "The safest way to avoid detection in stories is always right under the enemy's nose. It's the last place they'll think to look."],
["/pmwiki/pmwiki.php/Main/RisingWaterRisingTension", "Rising Water Rising Tension", "Slowly (or rapidly) rising flood waters create new hazards and a sense of urgency."],
["/pmwiki/pmwiki.php/Main/RiverOfInsanity", "River of Insanity", "Any river voyage or wilderness journey is a doomed expedition in which the characters alternately die go mad get lost go native or otherwise barely live to tell the tale."],
["/pmwiki/pmwiki.php/Main/RoadSignReversal", "Road Sign Reversal", "A villain or prankster mucks things up by flipping road signs so they point in the wrong direction."],
["/pmwiki/pmwiki.php/Main/RooftopConfrontation", "Rooftop Confrontation", "A fight on a rooftop. It will often end with someone falling off."],
["/pmwiki/pmwiki.php/Main/RopeBridge", "Rope Bridge", "If you see one you know one side is going to have the ropes cut or the planks are going to fall down."],
["/pmwiki/pmwiki.php/Main/TheRuinsICaused", "The Ruins I Caused", "After a big property-damage-causing event the main characters are seen on a cliff or plateau overlooking the ruins that resulted."],
["/pmwiki/pmwiki.php/Main/SalvagePirates", "Salvage Pirates", "The heroes are rescued! Okay not really; they're pirates who only want to loot their stuff."],
["/pmwiki/pmwiki.php/Main/SaveTheVillain", "Save the Villain", "You're gonna regret it..."],
["/pmwiki/pmwiki.php/Main/SawItInAMovieOnce", "Saw It in a Movie Once", "Where a character pulls off something crazy and unexpected and says he saw it in a movie once."],
["/pmwiki/pmwiki.php/Main/ScalingTheSummit", "Scaling the Summit", "A difficult treacherous climb up a tall steep mountain."],
["/pmwiki/pmwiki.php/Main/ScarySurpriseParty", "Scary Surprise Party", "Something nasty happens to a character (kidnapped in danger) but it turns out to be a surprise party."],
["/pmwiki/pmwiki.php/Main/ScrewThisImOuttaHere", "Screw This I'm Outta Here!", "Where a member of either the good guys or bad guys gets sick of it throws his hands in the air and walks away."],
["/pmwiki/pmwiki.php/Main/TheScrounger", "The Scrounger", "The guy The Captain turns to when he needs supplies."],
["/pmwiki/pmwiki.php/Main/SecretPath", "Secret Path", "When characters use a secret route to get somewhere often to get around obstacles or avoid being seen."],
["/pmwiki/pmwiki.php/Main/SecretPolice", "Secret Police", "You never saw them they didn't arrest you and that isn't your tongue they just cut off."],
["/pmwiki/pmwiki.php/Main/SecretUndergroundPassage", "Secret Underground Passage", "A hidden path often located under old houses or in bad guy lairs."],
["/pmwiki/pmwiki.php/Main/SeeTheWhitesOfTheirEyes", "See the Whites of Their Eyes", "In fiction if you can't see them you can't target them."],
["/pmwiki/pmwiki.php/Main/SentientCosmicForce", "Sentient Cosmic Force", "A sentient Background Magic Field of universal scale."],
["/pmwiki/pmwiki.php/Main/SeparatedFromTheAdults", "Separated From The Adults", "An easy convenient way to let a Kid Hero go on an adventure while still being fairly believable."],
["/pmwiki/pmwiki.php/Main/ShaggySearchTechnique", "Shaggy Search Technique", "The only way to find the secret passage is by sheer luck; leaning against that candle amazingly opens the door!"],
["/pmwiki/pmwiki.php/Main/SharkPool", "Shark Pool", "A body of water filled with any variety of unpleasant creatures such as alligators killer jellyfish piranha or sharks."],
["/pmwiki/pmwiki.php/Main/SheepInWolfsClothing", "Sheep in Wolf's Clothing", "Someone who's part-way transforming into a monster/zombie/robot/whatever will resist being on their side and will help their human friends."],
["/pmwiki/pmwiki.php/Main/ShipShapeShipwreck", "Shipshape Shipwreck", "No matter how ancient the shipwreck it'll be mostly intact on the ocean floor."],
["/pmwiki/pmwiki.php/Main/ShootTheFuelTank", "Shoot the Fuel Tank", "In fiction shooting a fuel tank makes it explode."],
["/pmwiki/pmwiki.php/Main/ShootTheRope", "Shoot the Rope", "When a character is about to be hanged the cavalry will come to the rescue and shoot the rope."],
["/pmwiki/pmwiki.php/Main/ShootYourMate", "Shoot Your Mate", "The hero is pretending to be on the bad guys side and his love interest or friend is held captive. The bad guy hands him a gun and tells him to shoot her."],
["/pmwiki/pmwiki.php/Main/ShootingGallery", "Shooting Gallery", "You have to shoot the dummies. But if you shoot the civilians you lose 100 points."],
["/pmwiki/pmwiki.php/Main/ShutUpAndSaveMe", "Shut Up and Save Me!", "With the heroine in danger the hero stops for a moment to start giving a speech or haranguing her."],
["/pmwiki/pmwiki.php/Main/SicEm", "Sic 'em", "After a minor victory we are treated to a scene of the Big Bad sending more minions after the hero."],
["/pmwiki/pmwiki.php/Main/SilentRunningMode", "Silent Running Mode", "The crew of a ship have to be as quiet as possible so enemy radar won't pick them up."],
["/pmwiki/pmwiki.php/Main/SingleMaltVision", "Single Malt Vision", "If you have been drinking and your foe seems to have undergone some sort of cloning effect so that it seems there are now many of him shoot the one in the middle."],
["/pmwiki/pmwiki.php/Main/SkeletonKey", "Skeleton Key", "A key that will open any door or lock; often shaped like a skeleton."],
["/pmwiki/pmwiki.php/Main/SkeletonKeyCard", "Skeleton Key Card", "You can open any locked door by taking out a credit card and jiggling it in the lock."],
["/pmwiki/pmwiki.php/Main/SlaveGalley", "Slave Galley", "The hero is enslaved and forced to work as a galley rower."],
["/pmwiki/pmwiki.php/Main/SlaveLiberation", "Slave Liberation", "The hero is on a mission to rescue slaves."],
["/pmwiki/pmwiki.php/Main/SleightOfTongue", "Sleight of Tongue", "The hero stuck in captivity is kissed by a sympathetic woman who passes some item to him in his mouth."],
["/pmwiki/pmwiki.php/Main/SlippedTheRopes", "Slipped the Ropes", "A tied up character reveals that he or she slipped their bonds ages ago."],
["/pmwiki/pmwiki.php/Main/SmokeOut", "Smoke Out", "Drop a smoke bomb and slip away while everybody's coughing."],
["/pmwiki/pmwiki.php/Main/SnowyScreenOfDeath", "Snowy Screen of Death", "You can tell when video cameras or visual feeds are destroyed because they get replaced with static."],
["/pmwiki/pmwiki.php/Main/SoftGlass", "Soft Glass", "When you throw yourself through a pane of glass shattering it you can get right up and keep going."],
["/pmwiki/pmwiki.php/Main/SoleSurvivor", "Sole Survivor", "The only person who survived a terrible tragedy or massacre."],
["/pmwiki/pmwiki.php/Main/SomethingWeForgot", "Something We Forgot", "The adventure's over everything's been taken care of...except the most important thing! D'OH!"],
["/pmwiki/pmwiki.php/Main/SpaceMarine", "Space Marine", "Standard FPS hero: A military man (often in bulky armour) who wields lots of big guns and kills lots of aliens."],
["/pmwiki/pmwiki.php/Main/SpySatellites", "Spy Satellites", "The omnipresent 'eye in the sky'."],
["/pmwiki/pmwiki.php/Main/SpyVersusSpy", "Spy Versus Spy", "Two opposing spy organizations with James Bond-like agents."],
["/pmwiki/pmwiki.php/Main/StabTheScorpion", "Stab the Scorpion", "A lethal attack that we think is meant for the hero is instead meant for something that was trying to kill him instead."],
["/pmwiki/pmwiki.php/Main/StateSec", "State Sec", "A sprawling government agent complete with Secret Police a paramilitary wing a propaganda division and more!"],
["/pmwiki/pmwiki.php/Main/StealthHiBye", "Stealth Hi/Bye", "When a character either suddenly appears or disappears close to someone when they weren't looking."],
["/pmwiki/pmwiki.php/Main/StormingTheCastle", "Storming the Castle", "It's time to gear up and assault the bad guy's home base!"],
["/pmwiki/pmwiki.php/Main/StrengthEqualsWorthiness", "Strength Equals Worthiness", "If you want someone or something to join your side you have to best it in physical combat first."],
["/pmwiki/pmwiki.php/Main/SuddenlyAlwaysKnewThat", "Suddenly Always Knew That", "A character suddenly has a skill they need with little or no explanation."],
["/pmwiki/pmwiki.php/Main/SuicideMission", "Suicide Mission", "When the situation is that desperate..."],
["/pmwiki/pmwiki.php/Main/SuperMultiPurposeRoom", "Super Multi-Purpose Room", "A mundane living room bedroom or small apartment that can be instantly transformed into a fully-functional Super Hero lair."],
["/pmwiki/pmwiki.php/Main/SuperWindowJump", "Super Window Jump", "To get to or from the scene in a hurry just jump through a window."],
["/pmwiki/pmwiki.php/Main/SupernaturalMartialArts", "Supernatural Martial Arts", "If you train hard enough you can channel mystic energies and blow up airplanes."],
["/pmwiki/pmwiki.php/Main/SurveillanceAsThePlotDemands", "Surveillance as the Plot Demands", "The bad guys have cameras everywhere even though nobody ever sees them."],
["/pmwiki/pmwiki.php/Main/SwampsAreEvil", "Swamps Are Evil", "About the horrors of certain swamplands..."],
["/pmwiki/pmwiki.php/Main/SwissCheeseSecurity", "Swiss Cheese Security", "Characters can enter the premises whenever the plot necessitates it despite presumably locked doors or obvious obstacles."],
["/pmwiki/pmwiki.php/Main/SwordAndGun", "Sword and Gun", "A character simultaneously wielding a gun in one hand and a sword in another or another combination of projectile and melee weapon."],
["/pmwiki/pmwiki.php/Main/SwordOverHead", "Sword over Head", "The good guy has the bad guy where he wants him raises his sword over his head... and can't go through with it."],
["/pmwiki/pmwiki.php/Main/TakeAMomentToCatchYourDeath", "Take a Moment to Catch Your Death", "The hero has just avoided a narrow scrape with death. Whew that was... BOOM!"],
["/pmwiki/pmwiki.php/Main/TakeItToTheBridge", "Take It to the Bridge", "Bridges like crossroads are imbued with plot significance."],
["/pmwiki/pmwiki.php/Main/TakeUpMySword", "Take Up My Sword", "The hero dies and a new hero takes up the old hero's mission."],
["/pmwiki/pmwiki.php/Main/TakingOverTheTown", "Taking Over the Town", "Villains cut a town off the outside world so they can use it for their own nefarious purposes."],
["/pmwiki/pmwiki.php/Main/TelecomTree", "Telecom Tree", "When the hero needs aid and calls his friends for help the friends will often save the hero time by calling others the hero has helped leading to a massive group response."],
["/pmwiki/pmwiki.php/Main/ThereWasADoor", "There Was a Door", "A character makes a dramatic entrance... by going through the wall."],
["/pmwiki/pmwiki.php/Main/TheyHaveTheScent", "They Have the Scent!", "When animals pick up the trail of someone they're pursuing leading to a chase."],
["/pmwiki/pmwiki.php/Main/ThisPageWillSelfDestruct", "This Page Will Self-Destruct", "When a message is designed to destroy itself after reading to keep it out of the wrong hands."],
["/pmwiki/pmwiki.php/Main/ThisWayToCertainDeath", "This Way to Certain Death", "A dangerous area is marked by the corpses or bones of those who previously went through it."],
["/pmwiki/pmwiki.php/Main/ThoseWereOnlyTheirScouts", "Those Were Only Their Scouts", "An initial victory over the enemy followed by the chilling realization that those were only the harbingers of doom."],
["/pmwiki/pmwiki.php/Main/ThreePointLanding", "Three-Point Landing", "Landing in a crouch with your feet wide apart and one hand on the ground."],
["/pmwiki/pmwiki.php/Main/ThrowAwayCountry", "Throw-Away Country", "When other countries are treated as one-shot disaster zones to show what could happen to the heroes beloved home and are never touched upon afterward."],
["/pmwiki/pmwiki.php/Main/ThrownFromTheZeppelin", "Thrown from the Zeppelin", "When the Big Bad calls investors in to finance his Evil Plan those who object are often killed."],
["/pmwiki/pmwiki.php/Main/TimeBomb", "Time Bomb", "A character must succeed within a time limit or bad things will happen."],
["/pmwiki/pmwiki.php/Main/TimeForPlanB", "Time for Plan B", "Our original plan failed. Time to blow stuff up or get the hell out of here!"],
["/pmwiki/pmwiki.php/Main/TiredOfRunning", "Tired of Running", "I've had it with being pursued. It's time to kick some ass!"],
["/pmwiki/pmwiki.php/Main/ToCatchHeroesHireVillains", "To Catch Heroes Hire Villains", "Heroes on the run for a major crime (that they may or may not have committed)? Send in the bad guys!"],
["/pmwiki/pmwiki.php/Main/ToTheBatpole", "To the Batpole!", "The heroes get to their base via a sequence of cool maneuvers before swinging into action."],
["/pmwiki/pmwiki.php/Main/TorchesAndPitchforks", "Torches and Pitchforks", "When the people get together in an angry mob to Burn the Witch! or kill the beast. Usually misguided."],
["/pmwiki/pmwiki.php/Main/TrainEscape", "Train Escape", "A train is used to end a chase either by crossing the tracks ahead of it just in time or by hopping aboard."],
["/pmwiki/pmwiki.php/Main/TraintopBattle", "Traintop Battle", "Battle atop a moving train. Common in Westerns and modern action flicks alike."],
["/pmwiki/pmwiki.php/Main/TrashLanding", "Trash Landing", "A character's fall is broken by landing in a dumpster."],
["/pmwiki/pmwiki.php/Main/TrespassingToTalk", "Trespassing to Talk", "Waiting in a character's home or office to confront them."],
["/pmwiki/pmwiki.php/Main/TrialOfTheMysticalJury", "Trial of the Mystical Jury", "The hero is put on trial."],
["/pmwiki/pmwiki.php/Main/TribalCarry", "Tribal Carry", "Tribesmen who capture characters will often carry them to their village like game on a pole."],
["/pmwiki/pmwiki.php/Main/TrickAndFollowPloy", "Trick-and-Follow Ploy", "Where you find out the location of the enemy's secret base by tricking an ally of his to go there and deliver some kind of communication."],
["/pmwiki/pmwiki.php/Main/TrojanHorse", "Trojan Horse", "Beware of Greeks bearing gifts."],
["/pmwiki/pmwiki.php/Main/TrojanPrisoner", "Trojan Prisoner", "The heroes pose as guards transporting a prisoner."],
["/pmwiki/pmwiki.php/Main/TrollBridge", "Troll Bridge", "The heroes must outwit someone guarding a bridge in order to cross."],
["/pmwiki/pmwiki.php/Main/TuckAndCover", "Tuck and Cover", "Saving someone else from an explosion by leaping on them and taking the blast for them."],
["/pmwiki/pmwiki.php/Main/UncertainDoom", "Uncertain Doom", "It isn't stated whether the character escapes a dangerous situation."],
["/pmwiki/pmwiki.php/Main/UnderestimatingBadassery", "Underestimating Badassery", "When the bad guys have no clue who they are messing with."],
["/pmwiki/pmwiki.php/Main/UndersideRide", "Underside Ride", "A character hitches a ride underneath a vehicle."],
["/pmwiki/pmwiki.php/Main/UnflinchingFaithInTheBrakes", "Unflinching Faith in the Brakes", "A character standing in the path of something dangerous will unflinchingly stand there knowing whatever it is will stop just inches from them."],
["/pmwiki/pmwiki.php/Main/UnguidedLabTour", "Unguided Lab Tour", "A protagonist walks into a top-secret workplace and only when the audience has had a complete lab tour does anyone notice the visitor."],
["/pmwiki/pmwiki.php/Main/UniversalDriversLicense", "Universal Driver's License", "The hero will know how to drive or operate any vehicle regardless of its general control scheme."],
["/pmwiki/pmwiki.php/Main/UnstoppableRage", "Unstoppable Rage", "When the hero gets utterly furious and uses that rage to completely own the bad guys."],
["/pmwiki/pmwiki.php/Main/UnwillingSuspension", "Unwilling Suspension", "A character is tied up and suspended from the ceiling."],
["/pmwiki/pmwiki.php/Main/VaporTrail", "Vapor Trail", "A hero uses the gas spilling out of a vehicle's gas-tank to ignite a trail back to the vehicle and destroy it."],
["/pmwiki/pmwiki.php/Main/VerticalKidnapping", "Vertical Kidnapping", "A character is kidnapped by someone from above."],
["/pmwiki/pmwiki.php/Main/VillainousRescue", "Villainous Rescue", "The heroes have been rescued by the villain."],
["/pmwiki/pmwiki.php/Main/VillainousValour", "Villainous Valour", "When a hero is unstoppable sometimes the bad guys will show otherwise heroic traits in taking him on."],
["/pmwiki/pmwiki.php/Main/ViolenceIsDisturbing", "Violence Is Disturbing", "When violence stops being cool and start being disturbing."],
["/pmwiki/pmwiki.php/Main/ViolenceIsTheOnlyOption", "Violence Is the Only Option", "In the action genre the only solution that works is kicking the bad guy's ass. Negotiation is useless or a trap."],
["/pmwiki/pmwiki.php/Main/WalkIntoMordor", "Walk into Mordor", "To enter the forbidden realm you are only allowed to use the most grueling methods available."],
["/pmwiki/pmwiki.php/Main/WalkThePlank", "Walk the Plank", "Pirate punishment of preference."],
["/pmwiki/pmwiki.php/Main/WasntThatFun", "Wasn't That Fun?", "A common utterance after surviving yet another escape."],
["/pmwiki/pmwiki.php/Main/WaterWakeup", "Water Wake-up", "You know it's not going to be a fun trip when you get a bucket of water thrown into your face after getting captured."],
["/pmwiki/pmwiki.php/Main/WaxOnWaxOff", "Wax On Wax Off", "Martial arts instruction disguised as menial chores."],
["/pmwiki/pmwiki.php/Main/WeaponizedCar", "Weaponized Car", "When a Cool Car has built in hidden weapons that can help the hero or villain out."],
["/pmwiki/pmwiki.php/Main/WeaponizedLandmark", "Weaponized Landmark", "A powerful weapon is built inside a famous landmark or monument."],
["/pmwiki/pmwiki.php/Main/WeaponsUnderstudies", "Weapons Understudies", "Only have the weapons and vehicles for one side available to you? Have both sides in your movie use them."],
["/pmwiki/pmwiki.php/Main/WildWilderness", "Wild Wilderness", "The woods nearby are very quiet on the outside but when you go in big adventures happen but no one outside notices."],
["/pmwiki/pmwiki.php/Main/WireDilemma", "Wire Dilemma", "The Time Bomb is ticking down. Which wire do you cut to disarm it and not blow yourself up?"],
["/pmwiki/pmwiki.php/Main/WorldTour", "World Tour", "When traveling the world is the adventure."],
["/pmwiki/pmwiki.php/Main/WrongWire", "Wrong Wire", "You cut the wrong wire and now the countdown's moving faster! Oh Crap!!"]];
    
    printWord(5);
    
    function printWord(words){
        for(var i=0; i<words; i++){
            
            var randomTrope = Math.floor(Math.random() * tropes.length);    
            var tropeString = '<h2><a href="https://tvtropes.org'+tropes[randomTrope][0]+'" target="_blank">'+tropes[randomTrope][1]+'</a></h2><p>'+tropes[randomTrope][2]+'</p><br />'
			$("#content").append(tropeString);
        }
    }
});
